### ISSUE TITLE
Running tflite model from cli

### ISSUE THREAD

**Issue by mattc-eostar** [mozilla/DeepSpeech#2594] opened 2019-12-11 16:01 UTC
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.6

Did the latest pip install --upgrade deepspeech and then downloaded the necessary model files from the release on github. 

Trying to run this command:
```
deepspeech --model deepspeech-0.6.0-models/output_graph.tflite --lm deepspeech-0.6.0-models/lm.binary --trie deepspeech-0.6.0-models/trie --audio barcodescanner-10.wav
```
but get this error:
```
Data loss: Can't parse deepspeech-0.6.0-models/output_graph.tflite as binary proto
Could not create model.
```

I am also trying this from within python but getting the same error. Can we not run tflite model files on desktop?

**Comment by reuben** [comment] 2019-12-11 16:26
> I am also trying this from within python but getting the same error. Can we not run tflite model files on desktop?

You can, but it requires a TFLite build of DeepSpeech, which currently is not super easy to install. I recently landed some changes to publish it as `deepspeech-tflite` on desktop platforms, and am in the process of testing them.

In the mean time, you can download the package directly from our build infra here: https://community-tc.services.mozilla.com/tasks/FppLZDBfQau8ThFZStaa7g#artifacts

In the "Artifacts" section on the right, choose the appropriate package for your Python version and install it.

**Comment by reuben** [comment] 2019-12-11 16:26
Closing as a duplicate of #2580.

**Comment by mattc-eostar** [comment] 2019-12-11 16:27
Great thank you!

**Closed by reuben** 2019-12-11 16:26 UTC
