### ISSUE TITLE
wav_filesize error on running DeepSpeech.py

### ISSUE THREAD

**Issue by disha3** [mozilla/DeepSpeech#1219] opened 2018-02-09 13:51 UTC
I get following error when running python3 DeepSpeech.py.

I have installed requirement.txt with pip3. 
Downloaded native client as per documentation.  
Tensorflow-gpu 1.4
Python 3.5
GTX 1070
CUDA 8
cuDNN 6
pandas (0.22.0) is installed
I am using common voice data which i have imported to wav.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 2525, in get_loc
>     return self._engine.get_loc(key)
>   File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'wav_filesize'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "DeepSpeech.py", line 1861, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "DeepSpeech.py", line 1818, in main
>     train()
>   File "DeepSpeech.py", line 1472, in train
>     next_index=lambda i: 
> 
>  COORD.get_next_index('train'))
> 
>   File "/home/divyaj/deepspeech/ds_code_clone/DeepSpeech/util/feeding.py", line 95, in __init__
>     self.files = self.files.sort_values(by="wav_filesize", ascending=ascending) \
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 3619, in sort_values
>     k = self.xs(by, axis=other_axis).values
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 2335, in xs
>     return self[key]
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2139, in __getitem__
>     return self._getitem_column(key)
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2146, in _getitem_column
>     return self._get_item_cache(key)
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 1842, in _get_item_cache
>     values = self._data.get(item)
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 3843, in get
>     loc = self.items.get_loc(item)
>   File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 2527, in get_loc
>     return self._engine.get_loc(self._maybe_cast_indexer(key))
>   File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'wav_filesize'

Pandas is giving error about wav_filesize. Any suggestions on how to fix it?

**Comment by lissyx** [comment] 2018-02-09 14:04
Isn't it a dupe of #1090 ?

**Comment by disha3** [comment] 2018-02-09 14:14
Oh yes, I get the error now @lissyx thanks for responding, I will try the solution given in #1090.

**Closed** 2018-02-09 14:20 UTC
Labels: invalid
