### ISSUE TITLE
building libdeepspeech with deepspeech as a git submodule

### ISSUE THREAD

**Issue by miguel-negrao** [mozilla/DeepSpeech#2209] opened 2019-06-25 10:05 UTC
Hi

It seems it is not possible to build libdeepspeech if deepspeech is a submodule of another git repo, as there won't be a .git folder in the deepspeech folder. 

```
bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so
Starting local Bazel server and connecting to it...
INFO: Analysed target //native_client:libdeepspeech.so (74 packages loaded, 5318 targets configured).
INFO: Found 1 target...
ERROR: /home/miguel/Development/IPL/investigacao/vad_check/libraries/tensorflow/native_client/BUILD:16:1: Executing genrule //native_client:ds_git_version failed (Exit 1)
realpath: /home/miguel/Development/IPL/investigacao/vad_check/libraries/deepspeech/native_client/../.git/: Not a directory
Target //native_client:libdeepspeech.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/miguel/Development/IPL/investigacao/vad_check/libraries/tensorflow/native_client/BUILD:68:1 Executing genrule //native_client:ds_git_version failed (Exit 1)
INFO: Elapsed time: 4.146s, Critical Path: 0.13s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
```

- Linux debian testing amd64 
- bazel: **Build label: 0.19.2**
- deepspeech repo: commit 4b29b78832036216b53f59b953639bde7cde7dfe (HEAD, tag: **v0.5.1**)
- tensorflow: commit 93dd14dce2e8751bcaab0a0eb363d55eb0cc5813 (HEAD -> for_deepspeech, **origin/r1.13**)

Directory structure

- ./top_repo/libraries/deepspeech
- ./top_repo/libraries/tensorflow
- ./top_repo/libraries/tensorflow/nativeclient -> ./top_repo/libraries/deepspeech/nativeclient (symlink)
- ./.git/modules/libraries/deepspeech
- ./.git/modules/libraries/tensorflow

**Comment by lissyx** [comment] 2019-06-25 10:16
@miguel-negrao Unfortunately, this is not a setup that we have, so it's not surprising it is broken. You might want to check and fix `native_client/ds_git_version.sh` for that.

**Comment by lissyx** [comment] 2019-06-25 10:19
> @miguel-negrao Unfortunately, this is not a setup that we have, so it's not surprising it is broken. You might want to check and fix `native_client/ds_git_version.sh` for that.

Be aware this is tricky because of how `bazel` works ...

**Comment by lissyx** [comment] 2019-06-25 10:26
>  as there won't be a .git folder in the deepspeech folder.

It seems that there won't be a **`.git` folder** but there is a **`.git` file** that points to the folder

**Comment by lissyx** [comment] 2019-06-25 10:34
@miguel-negrao Can you share the content of `.git` file for `deepspeech` and `tensorflow` repos?

**Comment by lissyx** [comment] 2019-06-25 10:36
Also, can you apply this patch, then in tensorflow directory do `bazel-genfiles/native_client/ds_*`, and then rebuild? You should have newer `bazel-genfiles/native_client/ds_version.h`, can you share?
```
diff --git a/native_client/ds_git_version.sh b/native_client/ds_git_version.sh
index 6fb6e41..c3e2c24 100755
--- a/native_client/ds_git_version.sh
+++ b/native_client/ds_git_version.sh
@@ -8,16 +8,24 @@ if [ `uname -o` = "Msys" ]; then
    export PATH="/c/Program Files/Git/bin/:${PATH}"
 fi
 
-DS_GIT_DIR="$(realpath "$(dirname "$(realpath "$0")")/../.git/")"
-if [ ! -d "${DS_GIT_DIR}" ]; then
+DS_GIT_DIR="$(realpath "$(dirname "$(realpath "$0")")/../.git")"
+if [ ! -d "${DS_GIT_DIR}" -a ! -f "${DS_GIT_DIR}" ]; then
    return 1
 fi;
 
-TF_GIT_DIR="$(realpath $(pwd)/tensorflow/../.git/)"
-if [ ! -d "${TF_GIT_DIR}" ]; then
+TF_GIT_DIR="$(realpath $(pwd)/tensorflow/../.git)"
+if [ ! -d "${TF_GIT_DIR}" -a ! -f "${TF_GIT_DIR}" ]; then
    return 1
 fi;
 
+# Handle the case of git submodules, the .git file contains the path to the tree
+if [ -f "${DS_GIT_DIR}" ]; then
+   DS_GIT_DIR=$(grep '^gitdir:' "${DS_GIT_DIR}" |cut -d ':' -f2)
+fi;
+if [ -f "${TF_GIT_DIR}" ]; then
+   TF_GIT_DIR=$(grep '^gitdir:' "${TF_GIT_DIR}" |cut -d ':' -f2)
+fi;
+
 DS_GIT_VERSION=$(git --git-dir="${DS_GIT_DIR}" describe --long --tags)
 if [ $? -ne 0 ]; then
    DS_GIT_VERSION=unknown;
@@ -29,6 +37,8 @@ if [ $? -ne 0 ]; then
 fi
 
 cat <<EOF
+// DS_GIT_DIR=${DS_GIT_DIR}
+// TF_GIT_DIR=${TF_GIT_DIR}
 #include <string>
 const char* ds_git_version() {
   return "${DS_GIT_VERSION}";
```

**Comment by lissyx** [comment] 2019-06-25 10:55
@miguel-negrao Hopefully https://github.com/mozilla/DeepSpeech/pull/2210 would work in your case, can you check it ?

**Comment by miguel-negrao** [comment] 2019-06-25 11:17
Was also working on a patch. :-) Will test your patch. I guess I will have to cherry-pick for v0.5.1.

**Comment by lissyx** [comment] 2019-06-25 11:34
> Was also working on a patch. :-) Will test your patch. I guess I will have to cherry-pick for v0.5.1.

Thanks. Also it'd be important to make sure `native_client/ds_graph_version.sh` needs or not this (it should not).

**Comment by miguel-negrao** [comment] 2019-06-25 12:11
It compiled but it didn't pick the versions correctly:

```
cat bazel-genfiles/native_client/ds_version.h
#include <string>
const char* ds_git_version() {
  return "unknown";
}
const char* tf_local_git_version() {
  return "unknown";
}
```


           DS_GIT_DIR=$(realpath "$(grep '^gitdir:' .git | cut -d':' -f2)") 

I think this will not work as the path inside the file is relative to that directory which will not match cwd. I think you need to build the path by placing the output of $(realpath "$(grep '^gitdir:' .git | cut -d':' -f2)")  after `$(dirname "$(realpath "$0")")/../` and the same for tf. Something similar to

   $(dirname "$(realpath "$0")")/../$(realpath "$(grep '^gitdir:' .git | cut -d':' -f2)")

**Comment by miguel-negrao** [comment] 2019-06-25 12:14
Actually `pushd $(dirname ${TF_GIT_DIR})` should take care of that... 

To test the script directly where should cwd be and what should $0 be ?

**Comment by lissyx** [comment] 2019-06-25 12:23
> To test the script directly where should cwd be and what should $0 be ?

that's dependant on bazel, that's exactly why I was fearing it would be tricky

**Comment by miguel-negrao** [comment] 2019-06-25 12:24
Ok, one thing is you need to do `cut -d'  ' -f2` instead of `cut -d':' -f2` otherwise you get a space at the start of the subpath.

**Comment by lissyx** [comment] 2019-06-25 12:28
> Ok, one thing is you need to do `cut -d' ' -f2` instead of `cut -d':' -f2` otherwise you get a space at the start of the subpath.

It should not be a problem, `realpath` should be able to deal with that ... With what got populated `$TF_GIT_DIR` and `$DS_GIT_DIR` in your case ? You can add `// ${TF_GIT_DIR}` and `// ${DS_GIT_DIR}` to the top of the `ds_version.h` generation in the script, remove the header and re-run.

**Comment by lissyx** [comment] 2019-06-25 12:28
> It compiled but it didn't pick the versions correctly:

Just to make sure, did you removed that file and ensured it was properly removed ? Bazel won't re-generate it if it exists.

**Comment by miguel-negrao** [comment] 2019-06-25 12:34
With the change from : to ' ' the script itself seems to work:

```
pwd
/home/miguel/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
 miguel   master  …  919f9f8bd54a24493eab207a22d11837  execroot  org_tensorflow  bash /home/miguel/Development/IPL/investigacao/vad_check/libraries/deepspeech/native_client/ds_git_version.sh 
~/Development/IPL/investigacao/vad_check/libraries/deepspeech ~/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
~/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
~/Development/IPL/investigacao/vad_check/libraries/tensorflow ~/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
~/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
#include <string>
const char* ds_git_version() {
  return "v0.5.1-1-g1686439";
}
const char* tf_local_git_version() {
  return "v1.13.1-13-g174b4760eb";
}
```
But it seems the build itself fails. Possibly the script is not being run with bash ? it seems not to find pushd and popd.

```
cd /home/miguel/Development/IPL/investigacao/vad_check/libraries/tensorflow/
bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so
INFO: Analysed target //native_client:libdeepspeech.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Executing genrule //native_client:ds_git_version:
native_client/ds_git_version.sh: 23: native_client/ds_git_version.sh: pushd: not found
grep: .git: No such file or directory
realpath: '': No such file or directory
native_client/ds_git_version.sh: 25: native_client/ds_git_version.sh: popd: not found
native_client/ds_git_version.sh: 28: native_client/ds_git_version.sh: pushd: not found
grep: .git: No such file or directory
realpath: '': No such file or directory
native_client/ds_git_version.sh: 30: native_client/ds_git_version.sh: popd: not found
fatal: not a git repository: ''
fatal: not a git repository: ''
Target //native_client:libdeepspeech.so up-to-date:
  bazel-bin/native_client/libdeepspeech.so
INFO: Elapsed time: 3.663s, Critical Path: 3.46s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 3 processes: 3 local.
INFO: Build completed successfully, 4 total actions
```

If I delete the file and tun build again, I get the same issue.

**Comment by lissyx** [comment] 2019-06-25 12:39
> But it seems the build itself fails. Possibly the script is not being run with bash ? it seems not to find pushd and popd.

Yeah, shebang is /bin/sh. Can you change it and confirm it works on your side ?


> With the change from : to ' ' the script itself seems to work:

Looks odd to me, but ... I'll update my PR, can you re-apply from scratch and re-confirm after ?

**Comment by miguel-negrao** [comment] 2019-06-25 12:39
```
file /bin/sh
/bin/sh: symbolic link to dash
```

**Comment by lissyx** [comment] 2019-06-25 12:41
> ```
> file /bin/sh
> /bin/sh: symbolic link to dash
> ```

Yeah, but:
 - I'm not sure `dash` provides `pushd`/`popd`
 - It' bad practice asking for `/bin/sh` and running `bash`-compatible and expecting it to work

**Comment by miguel-negrao** [comment] 2019-06-25 12:50
> Looks odd to me, but ... I'll update my PR, can you re-apply from scratch and re-confirm after ?

text inside file is `gitdir: ../../.git/modules/libraries/tensorflow`
with -d':'  you will get ` ../../.git/modules/libraries/tensorflow` (leading space)
with -d' ' you will get  `../../.git/modules/libraries/tensorflow`

I can confirm that changing to `/bin/bash` compiling works and generates correct versions. Also I can confirm that git versions are not generated with ':' but are generated with ' ':

with `-d ':'`
```
 miguel   174b476  …  vad_check  libraries  tensorflow  rm -f bazel-genfiles/native_client/ds_version.h 
 miguel   174b476  …  vad_check  libraries  tensorflow  bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so
INFO: Analysed target //native_client:libdeepspeech.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Executing genrule //native_client:ds_git_version:
realpath: ' ../../.git/modules/libraries/deepspeech': No such file or directory
realpath: ' ../../.git/modules/libraries/tensorflow': No such file or directory
fatal: not a git repository: ''
fatal: not a git repository: ''
Target //native_client:libdeepspeech.so up-to-date:
  bazel-bin/native_client/libdeepspeech.so
INFO: Elapsed time: 5.044s, Critical Path: 4.88s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 3 processes: 3 local.
INFO: Build completed successfully, 4 total actions
 miguel   174b476  …  vad_check  libraries  tensorflow  cat bazel-genfiles/native_client/ds_version.h 
#include <string>
const char* ds_git_version() {
  return "unknown";
}
const char* tf_local_git_version() {
  return "unknown";
}
```
The space causes an error on realpath.

with `-d ' '`
```
 miguel   174b476  …  vad_check  libraries  tensorflow  rm -f bazel-genfiles/native_client/ds_version.h 
 miguel   174b476  …  vad_check  libraries  tensorflow  bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so
INFO: Analysed target //native_client:libdeepspeech.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //native_client:libdeepspeech.so up-to-date:
  bazel-bin/native_client/libdeepspeech.so
INFO: Elapsed time: 5.084s, Critical Path: 4.97s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 3 processes: 3 local.
INFO: Build completed successfully, 4 total actions
 miguel   174b476  …  vad_check  libraries  tensorflow  cat bazel-genfiles/native_client/ds_version.h 
#include <string>
const char* ds_git_version() {
  return "v0.5.1-1-g1686439";
}
const char* tf_local_git_version() {
  return "v1.13.1-13-g174b4760eb";
}
 ```

**Comment by lissyx** [comment] 2019-06-25 12:54
> Also I can confirm that git versions are not generated with ':' but are generated with ' ':

Maybe I was not passing quotes when testing that. Anyway, I did re-push my PR with proper `-d ' '` and `/bin/bash` shebang, can you ensure you reproduce proper build from scratch after applying this one?

**Comment by miguel-negrao** [comment] 2019-06-25 12:57
Sorry, still not working because I forgot to mention one issue: you need to silence pushd and popd:

    pushd $(dirname ${DS_GIT_DIR}) > /dev/null
    popd > /dev/null

Currently 81a09cc doens't build because of that.

```
cat bazel-genfiles/native_client/ds_version.h 
/home/miguel/Development/IPL/investigacao/vad_check/libraries/deepspeech /home/miguel/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
/home/miguel/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
/home/miguel/Development/IPL/investigacao/vad_check/libraries/tensorflow /home/miguel/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
/home/miguel/.cache/bazel/_bazel_miguel/919f9f8bd54a24493eab207a22d11837/execroot/org_tensorflow
#include <string>
const char* ds_git_version() {
  return "v0.5.1-1-gfc84863";
}
const char* tf_local_git_version() {
  return "v1.13.1-13-g174b4760eb";
}
```

**Comment by lissyx** [comment] 2019-06-25 12:59
Oh yeah, forgot that. I told you it was tricky :)

**Comment by miguel-negrao** [comment] 2019-06-25 13:00
yeah, I know... :-)

**Comment by lissyx** [comment] 2019-06-25 13:01
> yeah, I know... :-)

Re-pushed, sorry, should now be okay.

**Comment by miguel-negrao** [comment] 2019-06-25 13:03
fd156a6 is working fine. Thanks a lot for looking into this !

**Comment by lissyx** [comment] 2019-06-25 13:05
I'll wait for taskcluster build to finish and merge, but you can already cherry-pick that

**Comment by miguel-negrao** [comment] 2019-06-25 13:05
Will this go into v0.5.2 (when that is released) ?

**Comment by lissyx** [comment] 2019-06-25 13:07
> Will this go into v0.5.2 (when that is released) ?

No, there won't be any v0.5.2, it will be part of v0.6.0

**Closed** 2019-06-25 16:16 UTC

**Comment by reuben** [comment] 2019-06-25 16:17
How can I test this scenario?

**Comment by miguel-negrao** [comment] 2019-06-25 21:26
> How can I test this scenario?

Possibly something like

```
mkdir test
cd test
git init
git submodule add https://github.com/mozilla/DeepSpeech.git DeepSpeech
git submodule add https://github.com/mozilla/tensorflow.git tensorflow
cd tensorflow 
git checkout r1.13
```
and then building ?

**Comment by reuben** [comment] 2019-06-26 02:29
Yep, I figured it out, should have commented here after I got it working. I was making sure PR #2212 doesn't break things with submodules.

**Comment by reuben** [comment] 2019-06-26 02:29
Thanks!
