### ISSUE TITLE
An excessive boost to the words after the hot-word seem to get misinterpreted as individual letters

### ISSUE THREAD

**Issue by vchagari** [mozilla/DeepSpeech#3500] opened 2021-01-15 23:18 UTC
Issue Description:
I used client.py (native_client/python/client.py) to test the Deepspeech by providing an audio file to get the transcribed audio output. Audio file is 3seconds long and has a person name (susanne wilson) in it. At first I tested without giving the hot word and Deepspeech gave the output as "sean wilson", hence I tried by giving a hotword and a boost value -"susanne:5" and Deepspeech could able to decode the audio correctly (output came as susanne wilson), but in the further tests I did, I have seen a weird behaviour when i increased the boost value to 25 (susanne:25) and I saw the following output - "susanne e l oson". 

similarly i ran many tests for various audio files and when I increase the boost value (ex: 20 or higher) for a particular word that's there in the audio file, the next word in the sentence (transcribed output) are transcribed as letters. 

the same issue was reported in the discourse as well, but looks like it was never reported as a bug!. 
FR: https://discourse.mozilla.org/t/new-0-9-alphas-to-test-new-features/68134

How I ran Deepspeech on the setup:
python3 client.py --model deepspeech_data/deepspeech-0.9.3-models.pbmm --scorer deepspeech_data/deepspeech-0.9.3-models.scorer --audio test.wav --hot_words "susanne:25"

output:
DeepSpeech: v0.9.3-0-gf2e9c85
2021-01-14 21:21:51.170266: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations: AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-14 21:21:51.171547: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-01-14 21:21:51.194164: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 21:21:51.194496: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 SUPER computeCapability: 7.5
coreClock: 1.815GHz coreCount: 48 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 462.00GiB/s
2021-01-14 21:21:51.194507: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-14 21:21:51.195499: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-01-14 21:21:51.196457: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-01-14 21:21:51.196619: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-01-14 21:21:51.197642: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-01-14 21:21:51.198195: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-01-14 21:21:51.200299: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-14 21:21:51.200360: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 21:21:51.200660: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 21:21:51.200908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-01-14 21:21:51.397930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-14 21:21:51.397966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263] 0
2021-01-14 21:21:51.397970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0: N
2021-01-14 21:21:51.398103: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 21:21:51.398386: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 21:21:51.398640: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 21:21:51.398889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7033 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
Loaded model in 0.291s.
Loading scorer from files deepspeech-0.9.3-models.scorer
Loaded scorer in 0.000138s.
Adding hot-words
Running inference.
2021-01-14 21:21:51.481202: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
call susanne e l olson
Inference took 0.443s for 2.950s audio file.

Info: 
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: upstream (using pip3 in
stall)
- **TensorFlow version (use command below)**: 1.15.4
- **Python version**: Python 3.6.9
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.1/7.6.4.38
- **GPU model and memory**: NVIDIA-SMI 460.27.04    Driver Version: 460.27.04
- **Exact command to reproduce**:
- Deepspeech version: v0.9.3

**Comment by lissyx** [comment] 2021-01-28 13:35
@JRMeyer Does this really qualify as a bug?

**Comment by JRMeyer** [comment] 2021-01-28 15:36
it's not a bug, no. It's just undesired behavior -- a side-effect of the algorithm with extreme values. Any attempt to "fix" this problem would involve some ad hoc hacking of the algorithm, which isn't a good idea without a more sound mathematical understanding of what's going on.

That being said, the hotwords algorithm isn't set in stone, and it would be welcome for someone to propose a more robust algorithm. However, the current behavior isn't a real "bug".

**Comment by lissyx** [comment] 2021-01-28 15:38
@JRMeyer should we close ? cc @vchagari

**Comment by JRMeyer** [comment] 2021-01-28 15:55
agree to close

**Comment by lissyx** [comment] 2021-02-12 09:06
Closing and it will be highlighed in docs thanks to #3524

**Closed by lissyx** 2021-02-12 09:06 UTC
Labels: waiting-on-reporter

**Comment by Sarthak-Gholap** [comment] 2021-09-20 07:07
How does hotword get stored? I mean when we add hotword what process happens? Where does it get stored? Does it get updated in model?
