### ISSUE TITLE
Parameters for limiting and skipping samples in data-sets not working anymore

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#1565] opened 2018-09-20 11:09 UTC
Regression: https://github.com/mozilla/DeepSpeech/pull/1532/files#diff-2f5b069cc3a96ce123ef7356642acb29L99

**Comment by lissyx** [comment] 2020-03-31 13:58
Dupe of #2777 ?

**Comment by omerasif-itu** [comment] 2020-06-01 00:51
with reference to #2851, I tried 0.8.0a2 but still not able to get these flags working. Will it be available with final release?
  
**INSTALL**
`pip list`
`deepspeech-training      0.8.0a2         /content/DeepSpeech/training`

**Comment by lissyx** [comment] 2020-06-03 09:06
> with reference to #2851, I tried 0.8.0a2 but still not able to get these flags working. Will these be available with final release?
> 
> **INSTALL**
> `pip list`
> `deepspeech-training 0.8.0a2 /content/DeepSpeech/training`

This PR was not merged

**Comment by omerasif-itu** [comment] 2020-06-03 20:20
This could be handy for running experiments quickly. Till 0.8.0 will have to limit data manually. Anyways, Looking forward to it.

**Comment by kdavis-mozilla** [comment] 2020-07-01 07:54
@tilmankamp Is this going to be able to land in 0.8.0?

**Comment by tilmankamp** [comment] 2020-07-22 15:15
Limiting should be no problem to implement with the new data-set approach. 

A bigger and most probably insufficient change would be required for true skipping, as the trivial approach of "reading all samples until reaching skip offset" would not help on "running experiments quickly". Background: The current data-set approach interleaves all data-sets passed on the command line on the fly while reading them from start to end during training. Skipping forward would require reading all indices and sample sizes up front, sorting them, interleaving them and then skipping to the required position.

A common problem that we once solved by skipping was determining the maximum batch-size on a GPU. This could also be done by reversing all data-sets and the interleaving-code (training longest samples first). This turns out to be cheap to implement.

So I consider implementing (fixing) limiting, dropping skip support altogether and adding `--reverse_train`, `--reverse_dev`, `--reverse_test` flags to be able to test for batch sizes.

**Closed** 2020-07-24 09:26 UTC
Labels: bug
