### ISSUE TITLE
Segmentation Fault in the end of training

### ISSUE THREAD

**Issue by pandeydivesh15** [mozilla/DeepSpeech#528] opened 2017-04-15 09:48 UTC
This may be a silly question, but still I wanted to know about this. 
I am runnning the following command (also given in /bin/run-ldc93s1.sh script).
```
python -u DeepSpeech.py --importer ldc93s1 --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --export_dir ../sample
```

The Deep Speech model is running without any problem, but towards the end of the program, I am getting Segmentation Fault error.
```bash
I Training of Epoch 48 - loss: 4.790713
I Training of Epoch 49 - loss: 3.173421
I FINISHED Optimization - training time: 0:03:54
I Test of Epoch 50 - WER: 0.090909, loss: 4.00302886963, mean edit distance: 0.019231
I --------------------------------------------------------------------------------
I WER: 0.090909, loss: 4.003029, mean edit distance: 0.019231
I  - src: "she had your dark suit in greasy wash water all year"
I  - res: "she had your dark suit in greasy wash water al year"
I --------------------------------------------------------------------------------
I Exporting the model...
I Restored checkpoint at training epoch 51
Converted 14 variables to const ops.
308 ops in the final graph.
I Models exported at ../sample
Segmentation fault (core dumped)
```

Any thoughts?

**Comment by kdavis-mozilla** [comment] 2017-04-15 13:22
This is a know problem and a duplicate of issue #440 You can take a look at #440 for more info. 

However, one should note that the run will complete fine, the problem is only how the code shuts down.

**Closed by kdavis-mozilla** 2017-04-15 13:22 UTC
Labels: duplicate
