### ISSUE TITLE
[Mozilla TensorFlow] Bazel build failure (if_cuda missing)

### ISSUE THREAD

**Issue by tarnh** [mozilla/DeepSpeech#2587] opened 2019-12-08 14:56 UTC
- **Have I written custom code**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Mozilla
- **TensorFlow version (use command below)**: 1.14
- **Python version**: 3.8.0
- **Bazel version (if compiling from source)**: 0.25.0
- **GCC/Compiler version (if compiling from source)**: gcc 9.2.0
- **CUDA/cuDNN version**: X
- **GPU model and memory**: Radeon RX 560
- **Exact command to reproduce**:
clone https://github.com/mozilla/tensorflow - branch 1.14
```
    cd $srcdir/tensorflow-r1.14
    ./configure

    ln -s ../DeepSpeech/native_client ./
    bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
```
Error:
```
Starting local Bazel server and connecting to it...
ERROR: ./tensorflow-r1.14/native_client/BUILD:3:1: file '@org_tensorflow//tensorflow:tensorflow.bzl' does not contain symbol 'if_cuda'
ERROR: ./tensorflow-r1.14/native_client/BUILD:85:1: name 'tf_cc_shared_object' is not defined
ERROR: error loading package 'native_client': Package 'native_client' contains errors
```

**Comment by lissyx** [comment] 2019-12-08 17:15
How did you ran `./configure` ? What options did you validate ? That looks like misconfiguration.

Also, upstream documents Bazel 0.24.1 for this TensorFlow version. Please stick to it.

**Comment by lissyx** [comment] 2019-12-08 17:16
@tarnh Can you explain why you want to rebuild from source ? What is not good from our prebuilt binaries ?

**Comment by tarnh** [comment] 2019-12-08 18:38
I use ArchLinux. Today Arch has many weak users, but when you've started 10 years ago you know the rule: _You shall have no other package managers before me_.

Any shit like `pip`, `conda` or `npm` can pollute my filesystem.

Additionally I prefer to understand what I'm doing. pip is just a black box.

**Comment by lissyx** [comment] 2019-12-08 18:45
> Any shit like `pip`, `conda` or `npm` can pollute my filesystem.

Nobody forces you to use them. There is a simple C++ tar as well.



> I use ArchLinux. Today Arch has many weak users, but when you've started 10 years ago you know the rule: _You shall have no other package managers before me_.

I tend to remember someone already made some Arch package. Maybe you should just look into that ?

**Comment by lissyx** [comment] 2019-12-08 18:50
https://aur.archlinux.org/packages/libdeepspeech/
https://aur.archlinux.org/packages/deepspeech-models/

**Comment by tarnh** [comment] 2019-12-08 20:59
```
a) Flagged out-of-date & only binary
b) Flagged out-of-date
```
But I don't want to flame around !

What are the right TF_ options for for a minimal build without CUDA that ./configure doesn't asks interactive questions?

**Comment by lissyx** [comment] 2019-12-08 21:56
> What are the right TF_* options for for a minimal build without CUDA that `./configure` doesn't asks interactive questions?

Default options should be good. We don't need anything fancy. `TF_NEED_CUDA=0` to disable.

Please make sure you stick to the proper Bazel version.

**Comment by lissyx** [comment] 2019-12-08 21:56
> ```
> a) Flagged out-of-date & only binary
> b) Flagged out-of-date
> ```
> 
> 
> But I don't want to flame around !

I'm not sure what you mean here, "flame around".

**Comment by talnetd** [comment] 2019-12-10 03:03
>     * **Have I written custom code**: No
> 
>     * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch
> 
>     * **TensorFlow installed from (our builds, or upstream TensorFlow)**: Mozilla
> 
>     * **TensorFlow version (use command below)**: 1.14
> 
>     * **Python version**: 3.8.0
> 
>     * **Bazel version (if compiling from source)**: 0.25.0
> 
>     * **GCC/Compiler version (if compiling from source)**: gcc 9.2.0
> 
>     * **CUDA/cuDNN version**: X
> 
>     * **GPU model and memory**: Radeon RX 560
> 
>     * **Exact command to reproduce**:
>       clone https://github.com/mozilla/tensorflow - branch 1.14
> 
> 
> ```
>     cd $srcdir/tensorflow-r1.14
>     ./configure
> 
>     ln -s ../DeepSpeech/native_client ./
>     bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
> ```
> 
> Error:
> 
> ```
> Starting local Bazel server and connecting to it...
> ERROR: ./tensorflow-r1.14/native_client/BUILD:3:1: file '@org_tensorflow//tensorflow:tensorflow.bzl' does not contain symbol 'if_cuda'
> ERROR: ./tensorflow-r1.14/native_client/BUILD:85:1: name 'tf_cc_shared_object' is not defined
> ERROR: error loading package 'native_client': Package 'native_client' contains errors
> ```

It is simply your card (Radeon RX 560) is not supported yet. For now, TensorFlow only supports Nvidia CUDA APIs  but to make sure please feel free to check out the official TensorFlow GPU guide. And I will also try to reproduce your problem when I have access to my workstation with Nividia GTX cards to see if that's the code problem or card problem. 

GLHF

**Comment by talnetd** [comment] 2019-12-10 03:08
TensorFlow only supports the following instruction sets and APIs.

1.     NVIDIA® GPU drivers —CUDA 10.0 requires 410.x or higher.
2.     CUDA® Toolkit —TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0)
3.     CUPTI ships with the CUDA Toolkit.
4.     cuDNN SDK (>= 7.4.1)
5.     (Optional) TensorRT 5.0 to improve latency and throughput for inference on some models.

REF: https://www.tensorflow.org/install/gpu

**Comment by lissyx** [comment] 2019-12-10 07:46
There is no need for GPU support for running decent inference.

**Comment by tarnh** [comment] 2019-12-10 20:55
> For now, TensorFlow only supports Nvidia CUDA APIs but to make sure please feel free to check out the official TensorFlow GPU guide. And I will also try to reproduce your problem when I have access to my workstation with Nividia GTX cards to see if that's the code problem or card problem.

Obviously you are wrong.

**Comment by reuben** [comment] 2019-12-10 21:15
@tarnh this repository is governed by the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/). In particular, see the section "Be Respectful" in expected behaviors.

If you believe someone is wrong, either be constructive or don't say anything at all.

**Comment by baerbock** [comment] 2019-12-11 18:23
@reuben It may seem rude to interfere with other people's things. IMHO this applies to telnetd.

**Comment by reuben** [comment] 2019-12-11 23:04
They were trying to help, and were [actually correct](https://www.tensorflow.org/install/gpu#hardware_requirements), not that it matters.

In addition, a direct answer to the author's question of how to disable CUDA was already given in this issue. Instead of updating the issue to let us know if the problem still persists or was fixed, the author instead makes a disrespectful comment. This behavior is not acceptable.

@tarnh are you still seeing this issue after setting the environment variable @lissyx mentioned? Can this issue be closed?

**Comment by a-lunev** [comment] 2019-12-14 00:10
> How did you ran `./configure` ? What options did you validate ? That looks like misconfiguration.
> 
> Also, upstream documents Bazel 0.24.1 for this TensorFlow version. Please stick to it.

Today I tried to build Mozilla TensorFlow-1.14 with DeepSpeech 0.6.0 and faced the same issue.
Initially I used Bazel 0.25.2 because there is "check_bazel_version('0.24.1', '0.25.2')" line in tensorflow/configure.py file (I followed the instructions here: https://www.tensorflow.org/install/source ("Make sure to install a supported Bazel version: any version between _TF_MIN_BAZEL_VERSION and _TF_MAX_BAZEL_VERSION as specified in tensorflow/configure.py.")).

I tried "TF_NEED_CUDA=0" as you suggested. No effect in my case.
Then as you suggested I tried to downgrade Bazel down to 0.24.1, and this helped!
Now I found this: https://www.tensorflow.org/install/source#tested_build_configurations
(tensorflow-1.14.0: Bazel 0.24.1).
It seems https://www.tensorflow.org/install/source is confusing.

I suppose if @tarnh tries to downgrade Bazel to 0.24.1 like me, it should be fixed as well.

**Comment by lissyx** [comment] 2019-12-14 06:32
> I suppose if @tarnh tries to downgrade Bazel to 0.24.1 like me, it should be fixed as well.

Thanks for confirming it's likely what I asked for in the very first comment :-)

**Comment by lissyx** [comment] 2019-12-16 10:22
@tarnh Ping ? Can we get an update ? Can you confirm as @a-lunev reported that using the proper Bazel version does indeed unblok you ?

**Comment by lissyx** [comment] 2019-12-18 11:26
No feedback on the proposed solution 10 days ago that was confirmed to work by others. Closing, there's nothing actionable here.

**Closed by lissyx** 2019-12-18 11:26 UTC
