### ISSUE TITLE
Referencing DeepSpeech.0.9.3 NuGet Package in netcoreapp3.1 results in CS0246 'DeepSpeechClient' could not be found

### ISSUE THREAD

**Issue by aolszowka** [mozilla/DeepSpeech#3483] opened 2021-01-01 18:31 UTC
First thank you for this project.

I believe that this might be related to #3373 and as such I have pinged @stepkillah and @lissyx if this is a duplicate please feel free to close. In that thread, It seems like there are some concerns over how to best make this package cross platform, however the thread is incredibly long, is there a bullet list of specific items that are being fought though that can be helped? My use case is currently Windows only, but I would love for it to be as platform agnostic as possible.

I am attempting to use the prebuilt NuGet Package (From https://www.nuget.org/packages/DeepSpeech) in a .NET Core Project (specifically a netcoreapp3.1) however I am getting errors indicating that it cannot find DeepSpeechClient which would indicate something is not right with the Package Restore.

Specifically the error is

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'DeepSpeechClient' could not be found (are you missing a using directive or an assembly reference?)	PackageRefIssue	C:\GitHub\DeepSpeech093NetCorePackageRefIssue\PackageRefIssue\Program.cs	1	Active
```
It is unclear if this is an authoring issue with the package or there is an underlying NuGet PackageReference Issue. I will open an issue report on the NuGet Project as well.

I have created this public repository that shows the issue: https://github.com/aolszowka/DeepSpeech093NetCorePackageRefIssue/tree/main 

This issue can be hacked around by adding an AssemblyReference to DeepSpeechClient from the NuGet “GAC”. I have demonstrated this fix here: https://github.com/aolszowka/DeepSpeech093NetCorePackageRefIssue/tree/Workaround-Using-Assembly-Path however this is less than ideal as you are not leveraging the package manager.

The expectation is that you should be able to clone the above project (on the main branch) and be able to build without issue.

Thank you

**EDIT: The issue has been reported to NuGet here https://github.com/NuGet/Home/issues/10421

**Comment by lissyx** [comment] 2021-01-01 20:32
The .Net Core work is not finished / merged, i dont know if you can expect anything to work (I dont know .Net)

**Comment by aolszowka** [comment] 2021-01-01 20:53
It for sure works (that's what the work around does) and is able to transcribe the samples (well to the best of its ability). There definitely seems to be some type of packaging issue though for .NET Core.

**Comment by lissyx** [comment] 2021-01-01 21:11
Sorry, it's clearly out of my scope if knowledges, will have to wait either @carlfm01 has a look or i come back from pto on two weeks and can have a look.

**Comment by carlfm01** [comment] 2021-01-09 23:52
Net core WIP here https://github.com/mozilla/DeepSpeech/blob/2e16d388ce0445b9642718df579d19ec6a82abc3/native_client/dotnet/DeepSpeechClient/DeepSpeechClient.csproj#L4 by @stepkillah 

With that change on the csproj should work, sadly there was a severe issue in one of my apps that took all my time :(, so I couldn't help @stepkillah to finish the cluster stuff.

**Comment by carlfm01** [comment] 2021-01-09 23:58
Hello @aolszowka, thanks for the example, to support net core we need something similar to https://github.com/mozilla/DeepSpeech/pull/3100/files
It is harder to pack since it needs the native client for all the platforms it will support and not only Windows.

**Comment by stepkillah** [comment] 2021-01-10 08:07
I still want to finish PR for net core support, it's not too much left, but was lack of time, hope can pick that up on next week

**Comment by aolszowka** [comment] 2021-01-10 13:06
Thanks @carlfm01 and @stepkillah I will hold off (it wasn't pressing I was more just playing around with it for my sake) let me know if there is something I can do to help.

I feel like we keep this PR open until those changes are in, then we can test that they work and close it.

**Comment by lissyx** [comment] 2021-03-03 16:07
Dupe of #3285

**Closed** 2021-03-03 16:07 UTC
