### ISSUE TITLE
timstamp mismatch issue

### ISSUE THREAD

**Issue by Aravindraj92** [mozilla/DeepSpeech#2259] opened 2019-07-20 07:59 UTC
Hi i have ran the  ./deepspeech --json --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio ../audio/2830-3980-0043.wav

and iam getting following output : 

TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78
2019-07-20 11:59:17.350341: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-07-20 11:59:17.350972: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-07-20 11:59:17.351014: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-07-20 11:59:17.351303: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
{"metadata":{"confidence":31.5515},"words":[{"word":"experience","time":0.56,"duration":0.56},{"word":"proof","time":1.16,"duration":0.28},{"word":"this","time":1.48,"duration":0.0999999}]}

in this result, I couldn't understand the time and duration values 

{"metadata":{"confidence":31.5515},"words":[{"word":"experience","time":0.56,"duration":0.56},{"word":"proof","time":1.16,"duration":0.28},{"word":"this","time":1.48,"duration":0.0999999}]}

**Comment by lissyx** [comment] 2019-07-20 11:39
Can you elaborate? I don't see anything obvious.

**Comment by Aravindraj92** [comment] 2019-07-20 11:49
What is time and duration that json?

**Comment by lissyx** [comment] 2019-07-20 17:26
I can't really figure out how simpler it might be. In timestamp data, time is the time the word appears and duration is its length? Cc @dabinat who landed this

**Comment by dabinat** [comment] 2019-07-22 17:33
The unit for the timing is seconds.

But be aware that the times listed are when DeepSpeech figured out that a letter was being uttered. So it might be slightly later than the exact point at which the letter actually begins being spoken.

**Comment by lissyx** [comment] 2019-07-23 07:35
I'm going to close that since it's not a bug and the questions is addressed. Please @Aravindraj92 use Discourse if you have questions, we use Github for bugs only.

**Closed by lissyx** 2019-07-23 07:35 UTC
