### ISSUE TITLE
Show steps per epoch

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2784] opened 2020-02-23 01:11 UTC
I’m doing a lot of training tests on AWS and am frequently changing batch sizes and machine specs.

Because of this it’s difficult to keep track of how many steps there are in an epoch (I believe the algorithm is file count / batch size / GPU count) and therefore difficult for me to get an idea of what an appropriate speed per step is and what kind of time I should expect for the epoch to complete.

It would be useful to be able to see the total number of steps in the progress text, e.g. “Step: 1800 / 5000” or “Step: 1250 (37%)”

**Comment by reuben** [comment] 2020-02-23 07:15
The problem is that tf.data.Dataset is built with streaming to be able to handle very large datasets so it has no `__len__`. We could compute a number ourselves but it requires reimplementing (and keeping in sync) any tf.data logic that changes the length, like `filter` or the `drop_remainder` argument of some batching/windowing APIs.

**Comment by lissyx** [comment] 2020-03-24 16:45
@dabinat From @reuben's reply above, I don't think we can fix that. I'm closing, but feel free to re-open if you think we should really do the extra work described.

**Closed by lissyx** 2020-03-24 16:45 UTC
