### ISSUE TITLE
ds2-v2 with ldc93s1 test data

### ISSUE THREAD

**Issue by hoagy-davis-digges** [mozilla/DeepSpeech#479] opened 2017-03-31 16:32 UTC
I'm experimenting with the ldc93s1 dataset on the deepspeech 2 branch, I've modified the utils/importer files in the same as ted.py (changing ```numcep + (2 * numcep * numcontext)``` to ```numcep``` on lines 39 and 43). The model seems to train okay, and gets a near perfect prediction in training, but then spits out a much worse prediction with a WER of around .55 in the testing phase, which doesn't seem to make sense since its using the same sentence, do you know why this might be happening?

**Comment by reuben** [comment] 2017-03-31 20:05
My understanding is that there's a bug somewhere in the batch normalization implementation that causes the testing phase to not work correctly. I've been trying to narrow it down for a while now with no success. Currently I'm working on something else, but this problem is the last thing that needs to be fixed on the DS2 branch.

**Comment by hoagy-davis-digges** [comment] 2017-03-31 23:34
Cool, thanks!

**Closed** 2017-04-08 14:45 UTC

**Comment by pdcoded** [comment] 2017-04-20 16:28
Hey @hoagy-davis-digges , seems that you have sucessfully ran the ds2-v2 branch on ldc93s1 data . I am getting a weird Invalid argument error . here is the traceback ..can you help out or point to the code commit branch that worked for you

    '[' '!' -f DeepSpeech.py ']'
    '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
    python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --checkpoint_dir =ds2-v2
    Traceback (most recent call last):
    File "DeepSpeech.py", line 1602, in
    tf.app.run()
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
    File "DeepSpeech.py", line 1565, in main
    train()
    File "DeepSpeech.py", line 1405, in train
    step = session.run(global_step, feed_dict=feed_dict)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 891, in run
    run_metadata=run_metadata)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
    File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'is_training' with dtype bool
    [[Node: is_training = Placeholderdtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]]

Caused by op u'is_training', defined at:
File "DeepSpeech.py", line 1602, in
tf.app.run()
File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "DeepSpeech.py", line 1565, in main
train()
File "DeepSpeech.py", line 1340, in train
is_training_ph = tf.placeholder(tf.bool, name="is_training")
File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1502, in placeholder
name=name)
File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2149, in _placeholder
name=name)
File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
op_def=op_def)
File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in init
self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'is_training' with dtype bool
[[Node: is_training = Placeholderdtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]]
