### ISSUE TITLE
High GPU Memory-Usage but low volatile gpu-util with librivox training process?

### ISSUE THREAD

**Issue by bolt163** [mozilla/DeepSpeech#1354] opened 2018-04-24 08:53 UTC
while running into the  10th epoch  with the  run-librivox.sh(https://github.com/mozilla/DeepSpeech/blob/master/bin/run-librivox.sh), the problem happend, (the gpu memory were fully ocuppied while the Volatile GPU-Utilg  always  varied  from 0 to 100, and almost were  0 ) has any body meet the same problem?

below is the avg GPU resource usage monitoring curve,from the diagram, there were 4 available GPU resources, but the libri training program  uses  1.x（<2）  GPU  averagly...
![1524560313 1](https://user-images.githubusercontent.com/25170435/39177094-f8afe1ae-47e0-11e8-8f61-00d0c985ca4d.png)

my gpu host is configured with 4 Tesla K80 GPU, and there is no other  training job  competing for the gpu resources  except the  run-librivox.sh traing program 

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
Tue Apr 24 16:46:06 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:2A:00.0 Off |                   0* |
| N/A   35C    P0    61W / 149W |  10904MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:2B:00.0 Off |                   0* |
| N/A   46C    P0    79W / 149W |  10904MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:2E:00.0 Off |                   0* |
| N/A   35C    P0    65W / 149W |  10904MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:2F:00.0 Off |                   0* |
| N/A   48C    P0    74W / 149W |  10904MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                                                                                                                   
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
Tue Apr 24 16:46:11 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:2A:00.0 Off |                   0* |
| N/A   36C    P0   130W / 149W |  10904MiB / 11439MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:2B:00.0 Off |                   0* |
| N/A   47C    P0   150W / 149W |  10904MiB / 11439MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:2E:00.0 Off |                   0* |
| N/A   36C    P0   139W / 149W |  10904MiB / 11439MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:2F:00.0 Off |                   0* |
| N/A   48C    P0   128W / 149W |  10904MiB / 11439MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
                                                                                                                                                                   
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
Tue Apr 24 16:46:26 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:2A:00.0 Off |                   0* |
| N/A   36C    P0    69W / 149W |  10904MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:2B:00.0 Off |                   0* |
| N/A   47C    P0    80W / 149W |  10904MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:2E:00.0 Off |                   0* |
| N/A   34C    P0    59W / 149W |  10904MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:2F:00.0 Off |                   0* |

**Comment by priteshpj** [comment] 2018-04-26 12:01
I'm facing the same issue when I leave the AWS instance unattended. Guess GPU is going to sleep?

**Comment by lissyx** [comment] 2018-04-26 12:31
Running stuff on AWS I've often seen kicking-time minutes long on the first GPU use, so there might be some things happening in the underlying hardware that have a play here. @bolt163 10th epoch only? It might be the WER computation, that happens only on CPU.

**Comment by bolt163** [comment] 2018-04-26 12:50
@lissyx   in memory  the 5th epoch seems have the same problem, at that time  i didnot pay so much attention with it and killed it to restart  again  (seems every 5 epoch?)， 

 I referenced the solutions in the  above issue  https://github.com/mozilla/DeepSpeech/issues/776
"
python -u DeepSpeech.py \
    ...
    --display_step 0 \
    --validation_step 1 \
"
by  setting display_step 0 and validation_step 1,  the GPU  Volatile GPU-Utilg become normal
(while in the original run-librivox.sh   --display_step 1,    --validation_step 5 https://github.com/mozilla/DeepSpeech/blob/master/bin/run-librivox.sh ),  but there seems have a OOM， and i killed it then restarted。。。。

**Comment by lissyx** [comment] 2018-04-26 12:51
@bolt163 Kernel OOM or GPU OOM ?

**Comment by bolt163** [comment] 2018-04-26 12:51
GPU OOM

**Comment by lissyx** [comment] 2018-04-26 12:53
Means you have not enough. Default batch size 12 should be good for GPUs with 12GB RAM. Try to lower to batch size 10, and lower again if it's OOM'ing.

**Comment by bolt163** [comment] 2018-04-26 12:59
@lissyx thanks for you carefully  solutions,my Telsa K80 GPU memory is 11439MiB(nearly 12GB)， while before the 9th epoch,  there was  no problem,  i will try latter if OOM again

**Comment by bolt163** [comment] 2018-04-26 13:02
" It might be the WER computation, that happens only on CPU"—— is the  WER computation a bottleneck
cost  cpu times which lags the  training processing?  can the WER computation be moved into GPU with tensorflow ops to solve this problem?

**Comment by lissyx** [comment] 2018-04-26 13:06
@bolt163 For the WER, please refer to other discussions about it, it has already been explained better than I can do it :), but yes, bottleneck and no GPU implem for now.

**Comment by lissyx** [comment] 2018-04-26 13:07
https://github.com/mozilla/DeepSpeech/issues/776

**Comment by bolt163** [comment] 2018-04-28 01:42
@lissyx  while training with the "
python -u DeepSpeech.py 
...
--display_step 0 
--validation_step 1 
"
—— there exists many warnings like and i reveiwd the DeepSpeech code and can not figure out why the warning happens

"WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): xxxxx vs previous value: xxxxx. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize"

2018-04-27T19:33:06.335074679Z WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 72251 vs previous value: 72251. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.
2018-04-27T19:33:43.914540581Z WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 72251 vs previous value: 72251. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.
2018-04-27T19:34:33.581832876Z WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 72251 vs previous value: 72251. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.
2018-04-27T19:35:38.356122356Z WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 72251 vs previous value: 72251. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.
2018-04-27T19:37:06.705384628Z WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 72251 vs previous value: 72251. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.

**Comment by JJoving** [comment] 2018-06-07 07:06
@bolt163 I also encountered this problem. Have you solved it now?

**Comment by luckmoon** [comment] 2018-08-07 15:10
+1

**Comment by AkshitKhajuria** [comment] 2019-06-17 14:23
> @lissyx in memory the 5th epoch seems have the same problem, at that time i did not pay so much attention with it and killed it to restart again (seems every 5 epoch?)，
> 
> I referenced the solutions in the above issue #776
> "
> python -u DeepSpeech.py 
> ...
> --display_step 0 
> --validation_step 1 
> "
> by setting display_step 0 and validation_step 1, the GPU Volatile GPU-Utilg become normal
> (while in the original run-librivox.sh --display_step 1, --validation_step 5 https://github.com/mozilla/DeepSpeech/blob/master/bin/run-librivox.sh ), but there seems have a OOM after about 20 hours' training， and i kill it then restart again.

Hi @bolt163 , I'm also facing a similar problem, while the gpu memory usage is high, the volatile gpu utilisation is almost none. Can't have that.
Could you explain what does the --display_step and --validation_step mean? Could be very helpful.

**Comment by lissyx** [comment] 2019-06-17 14:51
>  Could you explain what does the --display_step and --validation_step mean? Could be very helpful.

As documented, they are indicating when the process of display and validation should be done.



> Hi @bolt163 , I'm also facing a similar problem, while the gpu memory usage is high, the volatile gpu utilisation is almost none. Can't have that.

Without more informations on your context, it's complicated to be definitive on a root cause here.

**Comment by AkshitKhajuria** [comment] 2019-06-17 16:22
Wow, that was a fast reply. 
Deep learning and tensorflow noob here.
I'm training a model with a batch size of 10000. The processes do show up in the gpu's with almost all of the memory being used on gpu 0, but almost zero utilisation, ocassionally fluctuating between 0 and 1. 
![Screenshot from 2019-06-17 21-35-55](https://user-images.githubusercontent.com/46970219/59619425-18b99880-9148-11e9-8cdf-b703e9aa9733.png)

I did search a couple of discussions that suggested input bottleneck and small batch size to be a possible cause but I've checked that's definitely not the case. 10000 seems a good batch size for 12+16GB of gpu memory and tensorflow placeholders take care of the input pipeline.
What could be the problem?

I'm using a server btw with x128 Intel Xeon Gold 6142 cpu's and 256 GB ram. Also 2 gpu's, an Nvidia P100 and another K40c, their potential being wonderfully wasted.

**Comment by lissyx** [comment] 2019-06-17 16:32
That's not just about the size, it depends on your data. Batch size this big, it feels weird. Make sure you have tensorflow-gpu properly installed (if all gpu memory is allocated by a python process it should be okay but still). And then what is made of your dataset? Batch size 64 is the max I can get for French with common voice and a few other dataset, on RTX2080Ti GPUs (11GB RAM)

**Comment by lissyx** [comment] 2019-08-20 15:20
Closing because it is likely outdated. Feel free to open a new issue if required.

**Closed by lissyx** 2019-08-20 15:20 UTC
