### ISSUE TITLE
Coral Dev Board support

### ISSUE THREAD

**Issue by lucalazzaroni** [mozilla/DeepSpeech#3363] opened 2020-10-06 15:17 UTC
I have a [Coral Dev Board](https://coral.ai/docs/dev-board/get-started/). I tried to follow the standard steps but obviously the `pip3 install deepspeech` command returns an error since there's not a compatible version for the Coral Dev Board. So I would like to know if it's possible to make deepspeech work on this board. I already saw #3064 and #2332, so I'm pretty pessimistic about it, but, since there has been no answer to these threads from June, I wonder if things have changed. 
Thanks in advance for your answers.

**Comment by ftyers** [comment] 2020-10-06 15:29
Hi @lucalazzaroni thanks for your interest, as @lissyx says this is probably not going to work in the short term. I suggest opening a post on [Discourse](https://discourse.mozilla.org/c/mozilla-voice-stt/) or joining us on [Matrix](https://chat.mozilla.org/#/room/#machine-learning:mozilla.org) if you are interested in participating in getting this working. I'll close this for now as a duplicate of #2332.

**Closed by ftyers** 2020-10-06 15:29 UTC
