### ISSUE TITLE
Batch norm in branch issue330_ds2 doesn't work across multiple GPU's

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#339] opened 2017-01-08 13:20 UTC
Running `run-wer-automation.sh` on the server for `issue330_ds2` yielded the error
```
Traceback (most recent call last):
  File "DeepSpeech.py", line 998, in <module>
    last_train_wer, last_dev_wer, hibernation_path = train()
  File "DeepSpeech.py", line 898, in train
    train_context = create_execution_context('train')
  File "DeepSpeech.py", line 679, in create_execution_context
    tower_results = get_tower_results(data_set, optimizer=optimizer, is_training=is_train)
  File "DeepSpeech.py", line 401, in get_tower_results
    calculate_accuracy_and_loss(batch_set, 0.0 if optimizer is None else dropout_rate, is_training)
  File "DeepSpeech.py", line 278, in calculate_accuracy_and_loss
    logits, output_length = BiRNN(batch_x, tf.to_int64(batch_seq_len), dropout, is_training)
  File "DeepSpeech.py", line 237, in BiRNN
    output = tf.contrib.layers.batch_norm(inputs=layer_1, decay=0.99, is_training=is_training)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 203, in batch_norm
    trainable=trainable)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 269, in model_variable
    caching_device=caching_device, device=device)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 233, in variable
    caching_device=caching_device)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1022, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 849, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 345, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 330, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/tensorflow-env/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 651, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable BatchNorm_2/beta does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

**Comment by kdavis-mozilla** [comment] 2017-01-08 13:22
@reuben  I haven't looked in any detail as to why this occurs; I just thought the error log would help in modifying the code for multiple GPU's (PS: This is with r0.11)

**Comment by reuben** [comment] 2017-01-10 12:21
I'd been testing with 0.12.0-rc0.

**Comment by kdavis-mozilla** [comment] 2017-01-10 12:24
On multiple GPU's?

**Comment by reuben** [comment] 2017-01-10 12:27
Multiples of zero :)

But I can reproduce this with two CPU towers, so hopefully I can still fix it.

**Comment by kdavis-mozilla** [comment] 2017-01-10 12:31
Ok, I'm (still) trying to get my personal 2xTitan X box up to test things like this (But it's looking more and more like there's a hardware problem.)

**Comment by reuben** [comment] 2017-01-10 12:52
This is weird. On the server, there should never be a `BatchNorm_2` scope. There's two batch norm layers, `BatchNorm` and `BatchNorm_1`, then we set `reuse_variables()` and create the model on the second tower, which should reuse the existing scopes. But it seems we're somehow creating the model twice on the same device and we end up trying to reuse a variable that doesn't exist.

This error makes sense in my local test because I'm using `available_devices = ['/cpu:0', '/cpu:0']`, but not on the server, where the GPUs are all different devices.

**Comment by reuben** [comment] 2017-01-13 18:33
The problem was simple: the Slim layers weren't creating their variables on the CPU. I fixed that in commit e5a5e2fc8d77eff0ad19608ec561b19ec93690da.

**Comment by reuben** [comment] 2017-01-13 18:33
I'm gonna hold off on closing this issue until a full test run is done on the server.

**Comment by reuben** [comment] 2017-03-28 13:43
Even though we're still seeing weird behavior of batch norm on the multi-GPU setup, it runs, so I'm gonna close this issue.

**Closed by reuben** 2017-03-28 13:43 UTC
