### ISSUE TITLE
TypeError: CreateModel() takes at most 2 arguments (5 given)

### ISSUE THREAD

**Issue by Pradii23** [mozilla/DeepSpeech#2898] opened 2020-04-10 05:47 UTC
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

**Comment by Pradii23** [comment] 2020-04-10 05:48
TypeError                                 Traceback (most recent call last)
<ipython-input-11-55eaea5c2806> in <module>()
      3 args = (model, alphabet)
      4 kwargs = {'N_FEATURES' : N_FEATURES, 'N_CONTEXT' : N_CONTEXT, 'BEAM_WIDTH' : BEAM_WIDTH}
----> 5 ds = Model(*args, **kwargs)
      6 model_load_end = timer() - model_load_start
      7 print('Loaded model in {:.3}s.'.format(model_load_end), file=sys.stderr)

/usr/local/lib/python3.6/dist-packages/deepspeech/__init__.py in __init__(self, *args, **kwargs)
     38         self._impl = None
     39 
---> 40         status, impl = deepspeech.impl.CreateModel(*args, **kwargs)
     41         if status != 0:
     42             raise RuntimeError("CreateModel failed with error code {}".format(status))


Can anyone please assist me in resolving this error ?

**Comment by reuben** [comment] 2020-04-10 06:15
You ignored the issue template that is meant for exactly this type of problem. Edit the first comment with the information that's asked there so we can have an idea of what's happening. But I can already say you're probably mixing incompatible versions.

**Comment by lissyx** [comment] 2020-04-14 09:31
> Can anyone please assist me in resolving this error ?

As reuben said, mixing incompatible versions. Since you did not cared to properly share informations, and this is not a bug, I'm closing. Please use Discourse as documented to seek for support.

**Closed by lissyx** 2020-04-14 09:31 UTC
