### ISSUE TITLE
Use tf.contrib.cudnn_rnn or at least tf.contrib.rnn.BlockLSTMCell

### ISSUE THREAD

**Issue by ekelsen** [mozilla/DeepSpeech#1110] opened 2017-12-15 01:17 UTC
https://github.com/mozilla/DeepSpeech/blob/cbc868346bd0a0c0e9745a978f5818364a33084c/DeepSpeech.py#L424

BasicLSTMCell is a reference implementation, it is quite slow and memory inefficient.  It would be much better to use https://www.tensorflow.org/api_docs/python/tf/contrib/cudnn_rnn (literally an order of magnitude faster)
or at least https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/LSTMBlockCell .

**Comment by kdavis-mozilla** [comment] 2017-12-15 01:24
Thanks for the heads up. But this is a duplicate of issue #885

**Closed by kdavis-mozilla** 2017-12-15 01:24 UTC

**Comment by ekelsen** [comment] 2017-12-15 01:27
Using LSTMBlockCell is literally a regex that might be worth doing if implementing cudnn is taking months...
