### ISSUE TITLE
Cocktail Party Noise

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#285] opened 2016-12-12 21:36 UTC
In day to day speech recognition scenarios, one of the biggest problems is human background noise. The human ability of focusing on just one voice out of many is named the [Cocktail party effect](https://en.wikipedia.org/wiki/Cocktail_party_effect). 

For the model to be able to mimic this ability (focusing on the dominant foreground voice), it is to be trained with samples augmented by human background noise.

It is to be figured out, how much noise is required, and if this noise could somehow be generated or is better to be sourced.

**Comment by sdkamat** [comment] 2016-12-12 21:57
Check out http://www.soundsnap.com/

**Comment by kdavis-mozilla** [comment] 2016-12-12 22:14
@sdkamat @tilmankamp We will need about as much, if not more, noise as we have speech to prevent the network form simply learning to subtract the limited sample of noise we feed it. So, we should have on the order of hundreds of hours of noise for TED, thousands for Fisher.

Thus, buying sounds at about $3 per min from [soundsnap](http://www.soundsnap.com/) won't scale to our needs (or finances). Collecting sounds organically at scale seems a far better solution.

However, before starting on this we must first get the TED test WER down to 10% level and optimize training the network.

**Comment by kdavis-mozilla** [comment] 2020-01-13 11:05
Dupe of #1536

**Closed by kdavis-mozilla** 2020-01-13 11:05 UTC
Labels: Priority: P3
