### ISSUE TITLE
ImportError: cannot import name 'Alphabet' from 'deepspeech_training.util.text'

### ISSUE THREAD

**Issue by filipecatraia** [mozilla/DeepSpeech#3134] opened 2020-07-07 10:44 UTC
If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no, I'm simply following the docs for 0.7.4.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Catalina 10.15.5
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: `pip`
- **TensorFlow version (use command below)**: `v1.15.0-92-g5d80e1e8e6 1.15.2`
- **Python version**: `3.7.8`
- **Bazel version (if compiling from source)**: not compiling
- **GCC/Compiler version (if compiling from source)**: not compiling
- **CUDA/cuDNN version**: no CUDA support, attempting to train/test on CPU
- **GPU model and memory**: Radeon Pro 555X 2GB DDR5 (probably unsupported, but it doesn't matter)
- **Exact command to reproduce**: `bin/import_cv2.py cv-corpus-5-2020-06-22/pt/`

I've cloned `DeepSpeech` and am attempting to follow the documentation to train a custom model. I got to the step [“Common Voice training data”](https://deepspeech.readthedocs.io/en/v0.7.4/TRAINING.html#common-voice-training-data) without hiccups.

After downloading the CV corpus for Portuguese (version `pt_53h_2020-06-22`), I unpacked it and tried running the `bin/import_cv2.py` command as seen above. The error I got is:

```
Traceback (most recent call last):
  File "bin/import_cv2.py", line 27, in <module>
    from deepspeech_training.util.text import Alphabet
ImportError: cannot import name 'Alphabet' from 'deepspeech_training.util.text' (<redacted>/DeepSpeech/training/deepspeech_training/util/text.py)
```

Checking that file manually, it is indeed lacking any `Alphabet` export.

Not sure if I did anything wrong, but my IDE also complains about the missing import.

**Comment by lissyx** [comment] 2020-07-07 11:01
Dupe of #3130

**Comment by lissyx** [comment] 2020-07-07 11:02
@filipecatraia Please ensure you have checked out `v0.7.4` tag, there should be no problem on that version.

**Comment by filipecatraia** [comment] 2020-07-07 21:21
Thanks @lissyx, that worked. I was working off `master` (and tried `v0.9.0-alpha.1`), as I assumed it'd work. Cheers!

**Comment by lissyx** [comment] 2020-07-07 22:17
> Thanks @lissyx, that worked. I was working off `master` (and tried `v0.9.0-alpha.1`), as I assumed it'd work. Cheers!

It usually does, except when we break it :)

**Closed by lissyx** 2020-07-07 22:17 UTC
