### ISSUE TITLE
Native_client support for Volta -- CUDA 9 and cuDNN 7?

### ISSUE THREAD

**Issue by aaronzira** [mozilla/DeepSpeech#946] opened 2017-11-06 07:10 UTC
Hi all, has anyone else tried working with Volta yet, or is there a plan for updates? It seems that native_client is set up to work with CUDA 8/cuDNN 5 or earlier, so I'm guessing that's why I've had no luck yet. Tried with tensorflow 1.4 using python 3.5/3.6, as CUDA 9 support weren't available in earlier versions.

**Comment by reuben** [comment] 2017-11-17 15:17
Will come once we update our code/builds to 1.4. Duplicate of #959. Feel free to reopen if needed.

**Closed by reuben** 2017-11-17 15:17 UTC

**Comment by lissyx** [comment] 2017-11-28 17:55
@aaronzira It seems upstream still defaults to CUDA 8 so we will stick with that version for the moment.

**Comment by reuben** [comment] 2017-11-28 17:56
However, after the 1.4 update is landed, building from source with CUDA 9/cuDNN 7 works without problems (I tested it today).

**Comment by ArashHosseini** [comment] 2017-12-11 16:58
related to #1094 
@reuben ,
cuda8 and cudnn6...any help or solution for this issue?
