### ISSUE TITLE
segmentation fault on generate_trie

### ISSUE THREAD

**Issue by ailurus1991** [mozilla/DeepSpeech#1756] opened 2018-11-29 04:12 UTC
Hey guys,

I'm following this tutorial to use DeepSpeech on my own data (Japanese): https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830

I created the training/valid/test csv files correctly, and I got the alphabet, vocab and lm.binary. When I was trying to create the trie I got segmentation fault...

I followed this https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md to get the pre-built binaries with util/taskcluster.py, and use ./generate_trie alphabet.txt lm.binary trie. Did i miss something?

thanks

**Comment by MuruganR96** [comment] 2018-11-29 04:34
sir @ailurus1991 i think trie file not generate correctly. it is empty file. sir check once.
```
python3 util/taskcluster.py --branch " anything" --target new_native_client/
new_native_client/generate_trie alphabet.txt lm.binary vocab.txt trie

```
previously i was followed this command

**Comment by ailurus1991** [comment] 2018-11-29 05:53
@MuruganR96 hey dude thanks for ur reply. I found your generate_trie command have four args?

emmm, seems like the usage is :Usage: ./dest/generate_trie <alphabet> <lm_model> <trie_path> ?

BTW, I've tested this on a small english corpus still got segmentation fault... :(

**Comment by MuruganR96** [comment] 2018-11-29 07:51
i think my suggestion @ailurus1991 sir,  did you create your lm.arpa for your vocab.txt? and then lm.arpa convert binary format lm.binary. you will give input for this lm.binary with vocab.txt.
(or)
some memory consumption error.

**Comment by ailurus1991** [comment] 2018-11-29 08:08
@MuruganR96 yup, I followed the tutorial, and I created the arpa file by `./lmplz --text lm_corpus.txt --arpa words.arpa --o 4` and converted the arpa to binary by `./build_binary -T -s words.arpa lm.binary`. I didn't see any error output, so I think I got the right language model binary file...

**Comment by lissyx** [comment] 2018-11-29 08:18
>  Did i miss something?

Yes, share us more information. There's nothing we can do right now except telling you it works for us.
Like your system, a small testcase etc etc. Even just console output ...

**Comment by JRMeyer** [comment] 2018-11-30 00:36
@ailurus1991 - could be similar to #1745 ?

**Comment by lissyx** [comment] 2018-11-30 14:57
> I guess the problem is bin file generated by KenLM. @lissyx

Sure, but no stack trace, nothing we can work on so far. Can you share more informations ?

**Comment by ailurus1991** [comment] 2018-12-01 04:54
@lissyx I found a interesting thing. I added a english char in my Chinese vocab file, like this: https://github.com/ailurus1991/ds_files/blob/master/thchs30-vocabulary.txt

no seg fault anymore, so the problem is the encoding or something?

**Comment by lissyx** [comment] 2018-12-11 14:41
> no seg fault anymore, so the problem is the encoding or something?

Encoding, I doubt, but if you can try to investigate a bit more or share better STR and content for us to reproduce, we could fix that, maybe ?

**Comment by x0day** [comment] 2019-01-06 08:43
@lissyx I meet the same error here.

1. vocabulary.txt
```
我
你 我
他
我
你
```
2. alphabet2.txt
```
我
你
他
```

```
lmplz -o 2 --text vocabulary.txt --arpa words.arpa
build_binary -T -s words.arpa  lm.binary
generate_trie alphabet.txt lm.binary trie
```
last I meet the same error.

```
439388 segmentation fault  ~/native_client/generate_trie alphabet.txt lm.binary trie
```
then I run this command in gdb and get some debug info.

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000412431 in Scorer::save_dictionary(std::string const&) ()
```

**Comment by lissyx** [comment] 2019-01-06 10:54
@x0day Can you share your files so we can investigate ?

**Comment by lissyx** [comment] 2019-01-07 08:14
I'm not even able to reproduce your `lm.binary`:
```
alexandre@serveur:~/tmp/KenLM/issue1756$ ../kenlm-build/bin/lmplz -o 2 --text vocabulary.issue1756.txt --arpa words.arpa
=== 1/5 Counting and sorting n-grams ===
Reading /home/alexandre/tmp/KenLM/issue1756/vocabulary.issue1756.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 6 types 6
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:72 2:53974548480
/home/alexandre/tmp/KenLM/kenlm/lm/builder/adjust_counts.cc:52 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `s.n[j] == 0'.
Could not calculate Kneser-Ney discounts for 1-grams with adjusted count 4 because we didn't observe any 1-grams with adjusted count 3; Is this small or artificial data?
Try deduplicating the input.  To override this error for e.g. a class-based model, rerun with --discount_fallback

Abandon
```

**Comment by lissyx** [comment] 2019-01-07 08:18
> `lmplz -o 2 --text vocabulary.txt --arpa words.arpa`
> `build_binary -T -s words.arpa lm.binary`

This is just plain wrong, please checkout the documentation on how to rebuild a language model: https://github.com/mozilla/DeepSpeech/blob/master/data/lm/README.md

**Comment by x0day** [comment] 2019-01-07 09:01
@lissyx 
I can't generate the trie file.
you can check the lm.binary and the arpa file.

[arpa_and_binary.tar.gz](https://github.com/mozilla/DeepSpeech/files/2732054/arpa_and_binary.tar.gz)

**Comment by reuben** [comment] 2019-01-07 12:01
This should be fixed with the latest master. Please reopen this issue if you still see the bug with the new code.

**Closed** 2019-01-07 12:00 UTC
Labels: bug

**Comment by m13225311263** [comment] 2019-01-21 07:04
@lissyx
 Hi, In the lastest version v0.4.1.
I used the vocabulary and  the alphabet  from @ailurus1991 to test. https://github.com/ailurus1991/ds_files/blob/master/thchs30-vocabulary.txt
https://github.com/ailurus1991/ds_files/blob/master/thchs30-alphabet.txt

The trie file is generated. But, I do not think this file is right. Because the size of this file is too small, only 45KB.

Is it an another bug?

**Comment by lissyx** [comment] 2019-01-21 13:11
> @lissyx
> Hi, In the lastest version v0.4.1.
> I used the vocabulary and the alphabet from @ailurus1991 to test. https://github.com/ailurus1991/ds_files/blob/master/thchs30-vocabulary.txt
> https://github.com/ailurus1991/ds_files/blob/master/thchs30-alphabet.txt
> 
> The trie file is generated. But, I do not think this file is right. Because the size of this file is too small, only 45KB.
> 
> Is it an another bug?

That seems pretty obvious that this is not a bug. When working on that I got similar small files, I think it's fine.
