### ISSUE TITLE
Does batch size matter for inference?

### ISSUE THREAD

**Issue by jeremydvoss** [mozilla/DeepSpeech#2808] opened 2020-03-04 01:16 UTC
Linux 16 on GCP
deepspeech==0.7.0a2

I've trained my own network on a subset of the english common voice with these parameters:
```
language=enLimited10000
epochs=100
batch_size=128
lr=0.0001
dropout_rate=0.30
n_hidden=1000`
./DeepSpeech.py --train_files ../CommonVoice/$language/clips/train.csv  --dev_files ../CommonVoice/$language/clips/dev.csv --test_files ../CommonVoice/$language/clips/test.csv \
--epochs $epochs \
--test_batch_size $batch_size \
--train_batch_size $batch_size \
--dev_batch_size $batch_size \
--export_batch_size $batch_size \
--learning_rate $lr \
--export_dir $HOME/EXPORT_DIR/$language \
--dropout_rate $dropout_rate \
--n_hidden $n_hidden \
--train_cudnn \
--checkpoint_dir ~/.local/share/deepspeech/checkpoints$language/ \
--scorer data/lm/kenlm.scorer \

```
However when I do the inference, I get this error:
```
$ deepspeech --model ../EXPORT_DIR/enLimited10000/output_graph.pb --scorer ../DeepSpeech3/data/lm/kenlm.scorer --audio audio/2830-3980-0043.wav
Loading model from file ../EXPORT_DIR/enLimited10000/output_graph.pb
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-alpha.2-0-g9dd63d5
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2020-03-04 00:35:56.526314: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 0.0634s.
Loading scorer from files ../DeepSpeech3/data/lm/kenlm_BACKUP.scorer
Loaded scorer in 0.000286s.
Running inference.
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [128]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [128]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [128]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [128]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [128]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [128]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [128]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]

Inference took 0.486s for 1.975s audio file.

```
When I tried the inference for a smaller network where I used a batch size of 32, I got this:
```
$ deepspeech --model ../EXPORT_DIR/enLimited100/output_graph.pb --scorer ../DeepSpeech3/data/lm/kenlm.scorer --audio audio/2830-3980-0043.wav
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.0-alpha.2-0-g9dd63d5
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2020-03-04 01:07:25.709064: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 0.0576s.
Loading scorer from files ../DeepSpeech3/data/lm/kenlm_BACKUP.scorer
Loaded scorer in 0.000378s.
Running inference.
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [32]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [32]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [32]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [32]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [32]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [32]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]
Error running session: Invalid argument: Shapes of all inputs must match: values[0].shape = [1] != values[1].shape = [32]
         [[{{node cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/stack}}]]

Inference took 0.441s for 1.975s audio file.
```

So it seems to me like it's saying that a network trained on a batch size greater than 1 cannot infer for a single audio file. Is that true? That would mean I could only train for a batch size of 1, limiting the utilization of my gpus. Perhaps I am misunderstanding the difference between train- dev- test- and export- bash sizes.

**Comment by jeremydvoss** [comment] 2020-03-05 21:31
Thanks for the help! Looks like I need to completely retrain since my checkpoints are of a different shape now. Anyways to still use my old checkpoints?

**Comment by lissyx** [comment] 2020-03-05 21:40
> Thanks for the help! Looks like I need to completely retrain since my checkpoints are of a different shape now. Anyways to still use my old checkpoints?

I have not checked but it should be okay to just re-export without this argument. Pass checkpoint dur, no train, dev nor test csv arguments and `--load best ` that should suffice

**Comment by reuben** [comment] 2020-03-05 21:42
Checkpoints don't have a fixed batch size. You should be able to continue training with a different batch size. You can also just re-export with the same checkpoint you used but using --export_batch_size 1 to get a model that works with your clients.

**Comment by lissyx** [comment] 2020-03-06 12:17
Closing this since this is not a bug. Please next time, go to Discourse for support.

**Closed by lissyx** 2020-03-06 12:17 UTC
Labels: invalid
