### ISSUE TITLE
ds_ctcdecoder 0.4.1

### ISSUE THREAD

**Issue by talbs254** [mozilla/DeepSpeech#2608] opened 2019-12-17 16:23 UTC
Hi,
I'm trying to use version 0.4.1 of deepspeech, and when I write the command:
pip3 install $(python3 util/taskcluster.py --decoder)
I get the error message:

"
 HTTP error 404 while getting https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl
  Could not install requirement ds-ctcdecoder==0.4.1 from https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl because of error 404 Client Error: Not Found for url: https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl
Could not install requirement ds-ctcdecoder==0.4.1 from https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl for URL https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl
"

I tried to rebuild the artifact at make -C native_client/ctcdecode as suggested:
https://discourse.mozilla.org/t/could-not-install-requirement-ds-ctcdecoder-0-4-1/47013

but it wont work

**Comment by lissyx** [comment] 2019-12-17 16:44
> but it wont work

We need more than "it won't work".

**Comment by talbs254** [comment] 2019-12-17 16:47
Thanks for the fast reply.
I meant that I got the same error as before.

**Comment by lissyx** [comment] 2019-12-17 16:58
> Thanks for the fast reply.
> I meant that I got the same error as before.

Same error as before what ?

**Comment by talbs254** [comment] 2019-12-17 17:06
After the rebuild, I try to execute the command:
pip3 install $(python3 util/taskcluster.py --decoder)
and yet again get the error:

"
HTTP error 404 while getting https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl
Could not install requirement ds-ctcdecoder==0.4.1 from https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl because of error 404 Client Error: Not Found for url: https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl
Could not install requirement ds-ctcdecoder==0.4.1 from https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl for URL https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp36-cp36m-manylinux1_x86_64.whl
"

**Comment by lissyx** [comment] 2019-12-17 17:07
> After the rebuild, I try to execute the command:
> pip3 install $(python3 util/taskcluster.py --decoder)

That's not surprising, the rebuild is not going to upload the package to the repository. You need to `pip install path/to/built/whl`

**Comment by talbs254** [comment] 2019-12-17 17:56
> > After the rebuild, I try to execute the command:
> > pip3 install $(python3 util/taskcluster.py --decoder)
> 
> That's not surprising, the rebuild is not going to upload the package to the repository. You need to `pip install path/to/built/whl`

Could you elaborate on what is whl? where I can find it? and what exactly do I need to install? thanks.

**Comment by lissyx** [comment] 2019-12-17 17:57
> > > After the rebuild, I try to execute the command:
> > > pip3 install $(python3 util/taskcluster.py --decoder)
> > 
> > 
> > That's not surprising, the rebuild is not going to upload the package to the repository. You need to `pip install path/to/built/whl`
> 
> Could you elaborate on what is whl? where I can find it? and what exactly do I need to install? thanks.

Wheels are python package. You should have one produced under `native_client/` somewhere, named `ds_ctcdecoder*.whl`. Find it, `pip install <path/to/it>`.

**Comment by lissyx** [comment] 2019-12-17 17:58
I'm going to close this, since it is not a bug. You should have everything needed to move forward. Please seek further help on Discourse.

**Closed** 2019-12-17 17:58 UTC
