### ISSUE TITLE
Training finished each time, after single epoch on AWS instance with GPU and Cuda 10 

### ISSUE THREAD

**Issue by xpowerman** [mozilla/DeepSpeech#2026] opened 2019-04-09 06:49 UTC
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 AWS AMI
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: from Pi
- **TensorFlow version (use command below)**: tensorflow-gpu-13.01
- **Python version**: 3.6
- **CUDA/cuDNN version**: CUDA 10
- **GPU model and memory**: NVIDIA Tesla M60 8Gb

Hi, I try to train DeepSpeech russian language model, I have about 100 hr of examples and transcriptions. I use AWS Machine learning instance with GPU for this. I run training with my Bash Script:
 
```
#!/bin/sh


python -u ./DeepSpeech/DeepSpeech.py \
  --train_files $1/train/train.csv \
  --dev_files $1/dev/dev.csv \
  --test_files $1/test/test.csv \
  --train_batch_size 12 \
  --dev_batch_size 8 \
  --test_batch_size 8 \
  --n_hidden 2048 \
  --epoch 25 \
  --learning_rate 0.0001 \
  --display_step 0 \
  --validation_step 1 \
  --dropout_rate 0.2367 \
  --default_stddev 0.046875 \
  --checkpoint_step 1 \
  --loglevel 0 \
  --wer_log_pattern "GLOBAL LOG: logwer('${COMPUTE_ID}', '%s', '%s', %f)" \
  --checkpoint_dir $1/checkpoints/ \
  --export_dir $1/results/model_export/ \
  --alphabet_config_path $1/alphabet.txt \
  --lm_binary_path $1/lm.binary \
  --lm_trie_path $1/trie \
  "$@"

```
Training starting. But after about 3 hours, it complete just one epoch 0 and stops with such message:

```
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
--------------------------------------------------------------------------------
WER: 7.000000, CER: 24.000000, loss: 230.188080
- src: "бергли"
- res: "та а с бы не от едикоесънта"
--------------------------------------------------------------------------------
WER: 4.000000, CER: 9.000000, loss: 47.428146
- src: "арестантам"
- res: "а с кое тот"
--------------------------------------------------------------------------------
WER: 3.000000, CER: 6.000000, loss: 7.510287
- src: "бенедикт"
- res: "я не де"
--------------------------------------------------------------------------------
WER: 3.000000, CER: 6.000000, loss: 8.610639
- src: "бенедикт"
- res: "не не де"
--------------------------------------------------------------------------------
WER: 3.000000, CER: 6.000000, loss: 8.976390
- src: "бенедикт"
- res: "не не де"
--------------------------------------------------------------------------------
WER: 3.000000, CER: 6.000000, loss: 9.158927
- src: "бенедикт"
- res: "бы не де"
--------------------------------------------------------------------------------
WER: 3.000000, CER: 5.000000, loss: 9.459328
- src: "леонато"
- res: "я а то"
--------------------------------------------------------------------------------
WER: 3.000000, CER: 6.000000, loss: 9.829212
- src: "бенедикт"
- res: "не не де"
--------------------------------------------------------------------------------
WER: 3.000000, CER: 5.000000, loss: 10.436997
- src: "леонато"
- res: "я не то"
--------------------------------------------------------------------------------
WER: 3.000000, CER: 6.000000, loss: 10.692052
- src: "бенедикт"
- res: "де не де"
--------------------------------------------------------------------------------
```

In spite of the fact that there are 25 epochs in my script. I can start trainig again, and it will train epoch 1 and stops again. And so on. 

Equal script work fine with this dataset on node with CPU. But very slow (about 24 hours per epoch).

So, what is the problem with my script or configuration. Why DeepSpeech training only single epoch and stops on my aws instance with cuda and gpu?

**Comment by lissyx** [comment] 2019-04-09 07:01
That's not a stop in what you pasted, it's just the validation step, and you asked for one validation step at each training step in your command-line. With those values of loss, i'd wonder if you are not triggering early stopping ? Can you try with a brand new checkpoint dir to ensure you don't have a stale checkpoint that messes around ?

**Comment by xpowerman** [comment] 2019-04-09 09:01
> That's not a stop in what you pasted, it's just the validation step, and you asked for one validation step at each training step in your command-line. With those values of loss, i'd wonder if you are not triggering early stopping ? Can you try with a brand new checkpoint dir to ensure you don't have a stale checkpoint that messes around ?

This situation happen exactly with new checkpoint dir. I have try to reduce learning rate, but the result was same.

Also, I have remove some parameters in my scripts, like here

```
python -u ./DeepSpeech/DeepSpeech.py \
  --train_files $1/train/train.csv \
  --dev_files $1/dev/dev.csv \
  --test_files $1/test/test.csv \
  --train_batch_size 12 \
  --dev_batch_size 8 \
  --test_batch_size 8 \
  --n_hidden 2048 \
  --epoch 25 \
  --learning_rate 0.0001 \
  --dropout_rate 0.2367 \
  --default_stddev 0.046875 \
  --checkppoint_step 1 \
  --loglevel 0 \
  --wer_log_pattern "GLOBAL LOG: logwer('${COMPUTE_ID}', '%s', '%s', %f)" \
  --checkpoint_dir $1/checkpoints/ \
  --export_dir $1/results/model_export/ \
  --alphabet_config_path $1/alphabet.txt \
  --lm_binary_path $1/lm.binary \
  --lm_trie_path $1/trie \
  "$@"
```
And run again, but the result is same. It train single epoch, and finish training with validation results. On CPU instance I have 10 epoch's completed with same dataset and script, and training process still continued.

**Comment by lissyx** [comment] 2019-04-09 09:03
>   --checkppoint_step 1 \

What's that ? Also, please post more complete logs, and enable more debugging, if we don't see anything we can't help you for sure.

**Comment by xpowerman** [comment] 2019-04-09 09:13
> > --checkppoint_step 1 \
> 
> What's that ? Also, please post more complete logs, and enable more debugging, if we don't see anything we can't help you for sure.

I'm sorry It's old version of script. I change this parameter and test again. There is same results. So what logs do you need? I paste everything from stdout before it stop?

**Comment by lissyx** [comment] 2019-04-09 09:14
> I paste everything from stdout before it stop?

Everything, including when it stops, because so far **I don't see it stopping**. Including ensuring the checkpoint directory is empty.

**Comment by lissyx** [comment] 2019-04-09 12:50
> So, it train single epoch, export model and finished(but --epoch is set to 25)

There's no error at all here, and the loss values would suggest that early stop did its work. At the expense of repeating myself, can you make sure of it by disabling early stop?

**Comment by lissyx** [comment] 2019-04-09 12:51
`--noearly_stop`

**Comment by reuben** [comment] 2019-04-09 12:51
The underlying problem is being masked by tf.train.Coordinator.stop_on_exception(). Please update to latest master and re-run to check. Also, the flags is now called `--epochs`, not `--epoch`.

**Comment by xpowerman** [comment] 2019-04-10 10:32
So, I update to latest master, change `--epoch` to `--epochs`, and run training again. It finish 0 epoch with error:

```
Use standard file APIs to delete files with this prefix.
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
    train_loss = run_set('train', train_init_op)
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[36048,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node tower_0/MatMul_4 (defined at ./DeepSpeech/DeepSpeech.py:68) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node tower_0/gradients/tower_0/lstm_fused_cell/BlockLSTM_grad/BlockLSTMGrad (defined at ./DeepSpeech/DeepSpeech.py:261) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'tower_0/MatMul_4', defined at:
  File "./DeepSpeech/DeepSpeech.py", line 833, in <module>
    tf.app.run(main)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./DeepSpeech/DeepSpeech.py", line 817, in main
    train()
  File "./DeepSpeech/DeepSpeech.py", line 400, in train
    gradients, loss = get_tower_results(iterator, optimizer, dropout_rates)
  File "./DeepSpeech/DeepSpeech.py", line 252, in get_tower_results
    avg_loss = calculate_mean_edit_distance_and_loss(iterator, i, dropout_rates, reuse=i>0)
  File "./DeepSpeech/DeepSpeech.py", line 185, in calculate_mean_edit_distance_and_loss
    logits, _ = create_model(batch_x, batch_seq_len, dropout, reuse=reuse)
  File "./DeepSpeech/DeepSpeech.py", line 153, in create_model
    layers['layer_6'] = layer_6 = dense('layer_6', layer_5, Config.n_hidden_6, relu=False)
  File "./DeepSpeech/DeepSpeech.py", line 68, in dense
    output = tf.nn.bias_add(tf.matmul(x, weights), bias)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2455, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5333, in mat_mul
    name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[36048,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node tower_0/MatMul_4 (defined at ./DeepSpeech/DeepSpeech.py:68) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node tower_0/gradients/tower_0/lstm_fused_cell/BlockLSTM_grad/BlockLSTMGrad (defined at ./DeepSpeech/DeepSpeech.py:261) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```
And exit.

**Comment by lissyx** [comment] 2019-04-10 10:34
> shape[36048,35]

Can you try reducing batch size? Your GPU has only 8GB of memory, that might explain.

**Comment by xpowerman** [comment] 2019-04-11 04:03
So, I reduce train batch size from 12 to 6, dev and test batch size from 8 to 4. And after 0 epoch have same error.

```
Use standard file APIs to delete files with this prefix.
Epoch 0 | Elapsed Time: 2:50:23 | Steps: 4607 | Loss: 87.997542                                                                                                                                            T
raceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[36930,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node tower_0/MatMul_4}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node tower_0/gradients/tower_0/lstm_fused_cell/BlockLSTM_grad/BlockLSTMGrad}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./DeepSpeech/DeepSpeech.py", line 833, in <module>
    tf.app.run(main)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./DeepSpeech/DeepSpeech.py", line 817, in main
    train()
  File "./DeepSpeech/DeepSpeech.py", line 511, in train
    train_loss = run_set('train', train_init_op)
  File "./DeepSpeech/DeepSpeech.py", line 482, in run_set
    feed_dict=feed_dict)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[36930,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node tower_0/MatMul_4 (defined at ./DeepSpeech/DeepSpeech.py:68) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node tower_0/gradients/tower_0/lstm_fused_cell/BlockLSTM_grad/BlockLSTMGrad (defined at ./DeepSpeech/DeepSpeech.py:261) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'tower_0/MatMul_4', defined at:
  File "./DeepSpeech/DeepSpeech.py", line 833, in <module>
    tf.app.run(main)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./DeepSpeech/DeepSpeech.py", line 817, in main
    train()
  File "./DeepSpeech/DeepSpeech.py", line 400, in train
    gradients, loss = get_tower_results(iterator, optimizer, dropout_rates)
  File "./DeepSpeech/DeepSpeech.py", line 252, in get_tower_results
    avg_loss = calculate_mean_edit_distance_and_loss(iterator, i, dropout_rates, reuse=i>0)
  File "./DeepSpeech/DeepSpeech.py", line 185, in calculate_mean_edit_distance_and_loss
    logits, _ = create_model(batch_x, batch_seq_len, dropout, reuse=reuse)
  File "./DeepSpeech/DeepSpeech.py", line 153, in create_model
    layers['layer_6'] = layer_6 = dense('layer_6', layer_5, Config.n_hidden_6, relu=False)
  File "./DeepSpeech/DeepSpeech.py", line 68, in dense
    output = tf.nn.bias_add(tf.matmul(x, weights), bias)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2455, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5333, in mat_mul
    name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[36930,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node tower_0/MatMul_4 (defined at ./DeepSpeech/DeepSpeech.py:68) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node tower_0/gradients/tower_0/lstm_fused_cell/BlockLSTM_grad/BlockLSTMGrad (defined at ./DeepSpeech/DeepSpeech.py:261) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```
Is there some way or formula to calculate batch size for my environment, or a reason of this error not a batch size?

**Comment by kdavis-mozilla** [comment] 2019-04-11 06:37
@xpowerman Two questions:

- Are you still using "n_hidden 2048" or something bigger?
- What's the longest, in seconds, audio clip you are training on?

**Comment by xpowerman** [comment] 2019-04-11 07:18
I'm using n_hidden 2048. The longest audioclip in seconds is 147 seconds. But most of audioclips less then 15 seconds.

**Comment by kdavis-mozilla** [comment] 2019-04-11 07:37
Consider not training on any clips over 10 seconds. I think that, and selecting a reasonable batch size, should solve this problem.

**Comment by xpowerman** [comment] 2019-04-11 10:14
I train on same dataset on CPU, there is no errors. Is it only GPU issue?

**Comment by kdavis-mozilla** [comment] 2019-04-11 10:20
You are running out of memory on your GPU as it has access to less memory than your CPU.

**Comment by xpowerman** [comment] 2019-04-11 10:26
Is there any way to calculate batch size. On my instance with CPU i have 32GB of memory, and with batch sizes 12:8:8 there is no ResourceExhaustedError on same dataset. Is batch sizes 3:2:2 is fit for GPU with 8GB of memory, or it is only possible to calculate it by practical consideration?

**Comment by reuben** [comment] 2019-04-11 11:10
You can flip the sort order in `util/feeding.py` so that the largest files go in the first batch, then you should see OOM errors much faster. The problem is that by having a few super long files, you're hurting the performance of your entire training run, as the batch size is fixed for the whole epoch, so it has to accommodate for the largest samples in the dataset.

Consider looking through your data and removing or splitting super long samples.

**Comment by reuben** [comment] 2019-04-11 11:11
And answering the question directly, no, there's no easy way to calculate it directly.

**Comment by lissyx** [comment] 2019-07-18 17:39
Looks like there is nothing more to act on here. Closing, please file a new issue if required.

**Closed by lissyx** 2019-07-18 17:39 UTC
