### ISSUE TITLE
API to return top-n best transcriptions

### ISSUE THREAD

**Issue by pradipcyb** [mozilla/DeepSpeech#2140] opened 2019-05-30 08:05 UTC
Is there an option to get the top-n (say 5) transcriptions returned by the model. If it is not currently implemented, can it be added as a feature? I need such a n-best list to rerank for a NLP problem that has a very limited corpora to develop a feasible language model. Thanks.

**Comment by kdavis-mozilla** [comment] 2019-05-30 12:37
Duplicate of #432

**Closed by kdavis-mozilla** 2019-05-30 12:37 UTC
