### ISSUE TITLE
import_cv2.py windows 10 error

### ISSUE THREAD

**Issue by sonfiree** [mozilla/DeepSpeech#2312] opened 2019-08-21 08:51 UTC
```
Traceback (most recent call last):
  File "import_cv2.py", line 172, in <module>
    _preprocess_data(PARAMS.tsv_dir, AUDIO_DIR, label_filter_fun, PARAMS.space_after_every_character)
  File "import_cv2.py", line 43, in _preprocess_data
    _maybe_convert_set(input_tsv, audio_dir, label_filter, space_after_every_character)
  File "import_cv2.py", line 106, in _maybe_convert_set
    for i, _ in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "C:\anaconda3\lib\multiprocessing\pool.py", line 748, in next
    raise value
  File "C:\anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "import_cv2.py", line 80, in one_sample
    frames = int(subprocess.check_output(['soxi', '-s', wav_filename], stderr=subprocess.STDOUT, shell=True))
  File "C:\anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['soxi', '-s', 'D:\\spet\\data\\clips\\common_voice_ru_18849089.wav']' returned non-zero exit status 1.
```

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below): tensorflow v1.14.0
- Python version: python 3.7
- Bazel version (if compiling from source): bazel 0.24.1
- CUDA/cuDNN version: CUDA 10.2

**Comment by lissyx** [comment] 2019-08-21 08:56
> subprocess.CalledProcessError: Command '['soxi', '-s', 'D:\\spet\\data\\clips\\common_voice_ru_18849089.wav']' returned non-zero exit status 1.

@sonfiree Can you run that command manually ?

**Comment by sonfiree** [comment] 2019-08-21 09:03
@lissyx no

**Comment by lissyx** [comment] 2019-08-21 09:15
> @lissyx no
> `soxi not found`

Well then install `sox` to have `soxi` ?

**Comment by sonfiree** [comment] 2019-08-21 09:18
`sox` install

**Comment by lissyx** [comment] 2019-08-21 09:33
> `sox` installed

So ? Does it works ?

**Comment by sonfiree** [comment] 2019-08-21 09:33
sox it`s work. Code not work

**Comment by sonfiree** [comment] 2019-08-21 09:34
windows 10
```
import wave
import contextlib			
with contextlib.closing(wave.open(wav_filename,'r')) as f:
   frames = f.getnframes()	
```

**Comment by lissyx** [comment] 2019-08-21 09:34
> sox it`s work. Code not work

Do you mind sharing more informations ? We can't do anything to help with "code not work".

**Comment by lissyx** [comment] 2019-08-21 09:43
> windows 10
> 
> ```
> import wave
> import contextlib			
> with contextlib.closing(wave.open(wav_filename,'r')) as f:
>    frames = f.getnframes()	
> ```

Sorry, but that is not giving more informations. Re-run the `soxi` command line. Does it works? Then re-run the importer? Share the output.

**Comment by sonfiree** [comment] 2019-08-21 10:09
`soxi` not work

**Comment by lissyx** [comment] 2019-08-21 10:13
> `soxi` not work

@sonfiree again, can you elaborate ? I'd really like to help you, but so far I'm spending more time asking you to just share us errors to **know** what's happening.

**Comment by sonfiree** [comment] 2019-08-21 10:15
> @sonfiree again, can you elaborate ? I'd really like to help you, but so far I'm spending more time asking you to just share us errors to **know** what's happening.

I showed the error on top.
`sox` installed, `soxi` not found

**Comment by lissyx** [comment] 2019-08-21 10:22
@sonfiree sorry but it's hard to do divination with that much details. Unfortunately you need to figure out how / why soxi is still not found. Is it in your PATH? Nobody on the team uses windows, and we only support training on Linux so far.

I'm sure it's just a PATH issue.

**Comment by lissyx** [comment] 2019-08-21 10:37
@sonfiree why did you close the issue?

**Comment by lissyx** [comment] 2019-08-21 10:41
The fact that we don't currently support training on Windows does not mean we don't care about you getting it. Before contributors sent us feedback / patches we had no build for windows at all, and now it's supported for inference.

**Comment by sonfiree** [comment] 2019-08-21 11:04
I will switch to linux.
Since on windows it does not even see gpu

**Comment by lissyx** [comment] 2019-08-21 11:08
> I will switch to linux.
> Since on windows it does not even see gpu

Have you installed `tensorflow-gpu` ?

**Comment by lissyx** [comment] 2019-08-21 11:08
There's Windows support on upstream, so you should be able to get that part working https://pypi.org/project/tensorflow-gpu/#files

**Comment by sonfiree** [comment] 2019-08-22 02:37
> Have you installed `tensorflow-gpu` ?

Yes.
numpy conflict version

**Comment by lissyx** [comment] 2019-08-22 06:29
> > Have you installed `tensorflow-gpu` ?
> 
> Yes.
> `numpy` conflict version

Can you elaborate ?

**Comment by sonfiree** [comment] 2019-08-22 06:56
> > > Have you installed `tensorflow-gpu` ?
> > 
> > 
> > Yes.
> > `numpy` conflict version
> 
> Can you elaborate ?
```
DeepSpeech - numpy == 1.15.4
TF 1.14.0 numpy == 1.16.2
```

**Comment by lissyx** [comment] 2019-08-22 07:05
> > > > Have you installed `tensorflow-gpu` ?
> > > 
> > > 
> > > Yes.
> > > `numpy` conflict version
> > 
> > 
> > Can you elaborate ?
> 
> ```
> DeepSpeech - numpy == 1.15.4
> TF 1.14.0 numpy == 1.16.2
> ```

You don't need `deepspeech` installed for training.

**Comment by sonfiree** [comment] 2019-08-22 07:39
> You don't need `deepspeech` installed for training.

I know.
Not build windows
`util/taskcluster.py`
`whl - not found`
linux - it`s work

**Comment by lissyx** [comment] 2019-08-22 07:44
> `util/taskcluster.py`
> `whl - not found`

I'm sorry, but it's too short to be helpful, can you share complete errors ?

**Comment by sonfiree** [comment] 2019-08-22 07:44
I can not regret, I switched to linux

**Comment by lissyx** [comment] 2019-08-22 07:48
Right, i'll close that since it's not a bug, hopefully somebody will find useful informations in it :)

**Closed by lissyx** 2019-08-22 07:48 UTC
Labels: invalid
