### ISSUE TITLE
linux_x86_64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by rimidalv** [mozilla/DeepSpeech#2054] opened 2019-04-15 17:50 UTC
For support and discussions, please use our Discourse forums.

If you've found a bug, or have a feature request, then please create an issue with the following information:

Have I written custom code (as opposed to running examples on an unmodified clone of the repository):

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04

TensorFlow installed from (our builds, or upstream TensorFlow): source code
git checkout origin/r1.13

TensorFlow version (use command below):
b'v1.13.1-10-g3e0cc5374d' 1.13.1

Python version: 3.6

Bazel version (if compiling from source): 0.21.0

GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

CUDA/cuDNN version: 10.0/7

GPU model and memory:
Four video card with same configuration:
description: VGA compatible controller
product: GP106 [GeForce GTX 1060 3GB]
vendor: NVIDIA Corporation
physical id: 0
bus info: pci@0000:05:00.0
version: a1
width: 64 bits
clock: 33MHz
capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
configuration: driver=nvidia latency=0

Exact command to reproduce:
**:~/DeepSpeech/native_client/python$ make bindings**
pip install --quiet numpy wheel==0.31.0 setuptools==39.1.0
PATH=:$PATH AS=as CC=gcc CXX=c++ LD=ld CFLAGS=" " LDFLAGS="-Wl,--no-as-needed '-Wl,-rpath,\$ORIGIN/lib/' -Wl,-rpath,\$ORIGIN" MODEL_LDFLAGS="-L/home/rimidalv/tensorflow/bazel-bin/native_client " MODEL_LIBS="-ldeepspeech "   python ./setup.py build_ext 
/home/rimidalv/anaconda3/envs/deep/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/home/rimidalv/anaconda3/envs/deep/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.5.0-alpha.5' to '0.5.0a5'
  normalized_version,
running build_ext
building 'deepspeech._impl' extension
swigging impl.i to impl_wrap.cpp
swig -python -c++ -keyword -o impl_wrap.cpp impl.i
creating temp_build
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rimidalv/anaconda3/envs/deep/lib/python3.6/site-packages/numpy/core/include -I../ -I./ -I/home/rimidalv/anaconda3/envs/deep/include/python3.6m -c impl_wrap.cpp -o temp_build/impl_wrap.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating temp_build/deepspeech
c++ -pthread -shared -B /home/rimidalv/anaconda3/envs/deep/compiler_compat -L/home/rimidalv/anaconda3/envs/deep/lib -Wl,-rpath=/home/rimidalv/anaconda3/envs/deep/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,--no-as-needed -Wl,-rpath,$ORIGIN/lib/ -Wl,-rpath,$ORIGIN temp_build/impl_wrap.o -L/home/rimidalv/tensorflow/bazel-bin/native_client -ldeepspeech -o temp_build/deepspeech/_impl.cpython-36m-x86_64-linux-gnu.so
> MANIFEST.in
SRC_FILE=temp_build/deepspeech/*.so; TARGET_LIB_DIR=temp_build/deepspeech/lib; MANIFEST_IN=MANIFEST.in; echo "Analyzing $SRC_FILE copying missing libs to $SRC_FILE"; echo "Maybe outputting to $MANIFEST_IN"; (mkdir $TARGET_LIB_DIR || true); missing_libs=""; for lib in $SRC_FILE; do if [ "Linux" = "Darwin" ]; then new_missing="$( (for f in $(otool -L $lib 2>/dev/null | tail -n +2 | awk '{ print $1 }' | grep -v '$lib'); do ls -hal $f; done;) 2>&1 | grep 'No such' | cut -d':' -f2 | xargs basename -a)"; missing_libs="$missing_libs $new_missing"; elif [ "Linux" = "" ]; then missing_libs="libdeepspeech.so"; else missing_libs="$missing_libs $(ldd  $lib | grep 'not found' | awk '{ print $1 }')"; fi; done; for missing in $missing_libs; do find /home/rimidalv/tensorflow/bazel-bin/ -type f -name "$missing" -exec cp {} $TARGET_LIB_DIR \; ; chmod +w $TARGET_LIB_DIR/*.so ; if [ ! -z "$MANIFEST_IN" ]; then echo "include $TARGET_LIB_DIR/$missing" >> $MANIFEST_IN; fi; done; if [ "Linux" = "Darwin" ]; then for lib in $SRC_FILE; do for dep in $( (for f in $(otool -L $lib 2>/dev/null | tail -n +2 | awk '{ print $1 }' | grep -v '$lib'); do ls -hal $f; done;) 2>&1 | grep 'No such' | cut -d':' -f2 ); do dep_basename=$(basename "$dep"); install_name_tool -change "$dep" "@rpath/$dep_basename" "$lib"; done; done; fi;
Analyzing temp_build/deepspeech/*.so copying missing libs to temp_build/deepspeech/*.so
Maybe outputting to MANIFEST.in
cat MANIFEST.in
include temp_build/deepspeech/lib/libdeepspeech.so
rm -f temp_build/*_wrap.o temp_build/Release/*_wrap.obj
AS=as CC=gcc CXX=c++ LD=ld CFLAGS=" " LDFLAGS="-Wl,--no-as-needed '-Wl,-rpath,\$ORIGIN/lib/' -Wl,-rpath,\$ORIGIN" MODEL_LDFLAGS="-L/home/rimidalv/tensorflow/bazel-bin/native_client " MODEL_LIBS="-ldeepspeech "   python ./setup.py bdist_wheel  
/home/rimidalv/anaconda3/envs/deep/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/home/rimidalv/anaconda3/envs/deep/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.5.0-alpha.5' to '0.5.0a5'
  normalized_version,
running bdist_wheel
running build
running build_ext
running build_py
file deepspeech.py (for module deepspeech) not found
copying ./__init__.py -> temp_build/deepspeech
copying ./client.py -> temp_build/deepspeech
copying ./impl.py -> temp_build/deepspeech
file deepspeech.py (for module deepspeech) not found
running egg_info
writing deepspeech.egg-info/PKG-INFO
writing dependency_links to deepspeech.egg-info/dependency_links.txt
writing entry points to deepspeech.egg-info/entry_points.txt
writing requirements to deepspeech.egg-info/requires.txt
writing top-level names to deepspeech.egg-info/top_level.txt
file deepspeech.py (for module deepspeech) not found
reading manifest file 'deepspeech.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'deepspeech.egg-info/SOURCES.txt'
installing to temp_build
running install
running install_lib
running install_egg_info
Copying deepspeech.egg-info to temp_build/deepspeech-0.5.0a5-py3.6.egg-info
running install_scripts
creating temp_build/deepspeech-0.5.0a5.dist-info/WHEEL
creating '/home/rimidalv/DeepSpeech/native_client/python/dist/deepspeech-0.5.0a5-cp36-cp36m-linux_x86_64.whl' and adding '.' to it
adding 'deepspeech/__init__.py'
adding 'deepspeech/_impl.cpython-36m-x86_64-linux-gnu.so'
adding 'deepspeech/client.py'
adding 'deepspeech/impl.py'
adding 'deepspeech/lib/libdeepspeech.so'
adding 'deepspeech-0.5.0a5.dist-info/entry_points.txt'
adding 'deepspeech-0.5.0a5.dist-info/top_level.txt'
adding 'deepspeech-0.5.0a5.dist-info/WHEEL'
adding 'deepspeech-0.5.0a5.dist-info/METADATA'
adding 'deepspeech-0.5.0a5.dist-info/RECORD'
removing temp_build
**(deep) rimidalv@rimidalv-desktop:~/DeepSpeech/native_client/python$ pip install dist/deepspeech***
**deepspeech-0.5.0a5-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform**.

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Comment by lissyx** [comment] 2019-04-15 18:10
According to your pip install of deepspeech-gpu this is python 3.6 and you try to install 3.7 build, that's not going to work. We already have 0.5.0a5 available on pypi why do you need to rebuild?

**Comment by lissyx** [comment] 2019-04-15 18:17
Please make sure you build a matching version and/or use `pip install - - upgrade deepspeech-gpu==0.5.0a5`

**Comment by rimidalv** [comment] 2019-04-15 18:21
because it isn't work :(

For example: 
~/DeepSpeech/native_client/python$ deepspeech -h
deepspeech: error while loading shared libraries: libdeepspeech.so: cannot open shared object file: No such file or directory

or

~/DeepSpeech/native_client$ deepspeech -h
deepspeech: error while loading shared libraries: libdeepspeech.so: cannot open shared object file: No such file or directory

or

$ pip install --upgrade deepspeech-gpu==0.5.0a5
Collecting deepspeech-gpu==0.5.0a5
  Downloading https://files.pythonhosted.org/packages/ff/27/4ddcf69338bc8efe5009c4237f8f410ba781d496228f395dffbd2bc2560c/deepspeech_gpu-0.5.0a5-cp36-cp36m-manylinux1_x86_64.whl (44.3MB)
    100% |████████████████████████████████| 44.3MB 305kB/s 
Requirement already satisfied, skipping upgrade: numpy>=1.7.0 in /home/rimidalv/anaconda3/envs/deep/lib/python3.6/site-packages (from deepspeech-gpu==0.5.0a5) (1.15.4)
Installing collected packages: deepspeech-gpu
  Found existing installation: deepspeech-gpu 0.4.1
    Uninstalling deepspeech-gpu-0.4.1:
      Successfully uninstalled deepspeech-gpu-0.4.1
Successfully installed deepspeech-gpu-0.5.0a5
(deep) rimidalv@rimidalv-desktop:~/tensorflow$ deepspeech -h
deepspeech: error while loading shared libraries: libdeepspeech.so: cannot open shared object file: No such file or directory

**Comment by lissyx** [comment] 2019-04-15 18:24
There's something seriously wrong on your system. What's `which deepspeech`?

**Comment by lissyx** [comment] 2019-04-15 18:24
Can you also `ldd $(which deepspeech) `?

**Comment by rimidalv** [comment] 2019-04-15 18:26
tensorflow$ which deepspeech
/home/rimidalv/anaconda3/envs/deep/bin/deepspeech

$ ldd $(which deepspeech)
	not a dynamic executable

**Comment by lissyx** [comment] 2019-04-15 18:30
Could you try outside of anaconda?

**Comment by lissyx** [comment] 2019-04-15 18:31
Also paste output of `LD_DEBUG=libs deepspeech - - version` ?

**Comment by rimidalv** [comment] 2019-04-15 18:45
I rebuild with python 3.6 and now I have got the same problem as like as I installed from pip

**(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client$ TFDIR=~ /tensorflow
(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client$ make deepspeech**
c++   -std=c++11 -o deepspeech `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/home/rimidalv/tensorflow/bazel-bin/native_client  -ldeepspeech  `pkg-config --libs sox`
**(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client$ cd python/
(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client/python$ cd ..
(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client$ PREFIX=/usr/local sudo make install**
[sudo] password for rimidalv: 
install -d /usr/local/lib
install -m 0644 /home/rimidalv/tensorflow/bazel-bin/native_client/libdeepspeech.so /usr/local/lib/
install -d /usr/local/bin
install -m 0755 deepspeech /usr/local/bin/
**(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client$ cd python/
(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client/python$ make bindings**
pip install --quiet numpy wheel==0.31.0 setuptools==39.1.0
PATH=:$PATH AS=as CC=gcc CXX=c++ LD=ld CFLAGS=" " LDFLAGS="-Wl,--no-as-needed '-Wl,-rpath,\$ORIGIN/lib/' -Wl,-rpath,\$ORIGIN" MODEL_LDFLAGS="-L/home/rimidalv/tensorflow/bazel-bin/native_client " MODEL_LIBS="-ldeepspeech "   python ./setup.py build_ext 
/home/rimidalv/anaconda3/envs/deep/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/home/rimidalv/anaconda3/envs/deep/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.5.0-alpha.5' to '0.5.0a5'
  normalized_version,
running build_ext
building 'deepspeech._impl' extension
swigging impl.i to impl_wrap.cpp
swig -python -c++ -keyword -o impl_wrap.cpp impl.i
creating temp_build
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rimidalv/anaconda3/envs/deep/lib/python3.6/site-packages/numpy/core/include -I../ -I./ -I/home/rimidalv/anaconda3/envs/deep/include/python3.6m -c impl_wrap.cpp -o temp_build/impl_wrap.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating temp_build/deepspeech
c++ -pthread -shared -B /home/rimidalv/anaconda3/envs/deep/compiler_compat -L/home/rimidalv/anaconda3/envs/deep/lib -Wl,-rpath=/home/rimidalv/anaconda3/envs/deep/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,--no-as-needed -Wl,-rpath,$ORIGIN/lib/ -Wl,-rpath,$ORIGIN temp_build/impl_wrap.o -L/home/rimidalv/tensorflow/bazel-bin/native_client -ldeepspeech -o temp_build/deepspeech/_impl.cpython-36m-x86_64-linux-gnu.so
> MANIFEST.in
SRC_FILE=temp_build/deepspeech/*.so; TARGET_LIB_DIR=temp_build/deepspeech/lib; MANIFEST_IN=MANIFEST.in; echo "Analyzing $SRC_FILE copying missing libs to $SRC_FILE"; echo "Maybe outputting to $MANIFEST_IN"; (mkdir $TARGET_LIB_DIR || true); missing_libs=""; for lib in $SRC_FILE; do if [ "Linux" = "Darwin" ]; then new_missing="$( (for f in $(otool -L $lib 2>/dev/null | tail -n +2 | awk '{ print $1 }' | grep -v '$lib'); do ls -hal $f; done;) 2>&1 | grep 'No such' | cut -d':' -f2 | xargs basename -a)"; missing_libs="$missing_libs $new_missing"; elif [ "Linux" = "" ]; then missing_libs="libdeepspeech.so"; else missing_libs="$missing_libs $(ldd  $lib | grep 'not found' | awk '{ print $1 }')"; fi; done; for missing in $missing_libs; do find /home/rimidalv/tensorflow/bazel-bin/ -type f -name "$missing" -exec cp {} $TARGET_LIB_DIR \; ; chmod +w $TARGET_LIB_DIR/*.so ; if [ ! -z "$MANIFEST_IN" ]; then echo "include $TARGET_LIB_DIR/$missing" >> $MANIFEST_IN; fi; done; if [ "Linux" = "Darwin" ]; then for lib in $SRC_FILE; do for dep in $( (for f in $(otool -L $lib 2>/dev/null | tail -n +2 | awk '{ print $1 }' | grep -v '$lib'); do ls -hal $f; done;) 2>&1 | grep 'No such' | cut -d':' -f2 ); do dep_basename=$(basename "$dep"); install_name_tool -change "$dep" "@rpath/$dep_basename" "$lib"; done; done; fi;
Analyzing temp_build/deepspeech/*.so copying missing libs to temp_build/deepspeech/*.so
Maybe outputting to MANIFEST.in
cat MANIFEST.in
include temp_build/deepspeech/lib/libdeepspeech.so
rm -f temp_build/*_wrap.o temp_build/Release/*_wrap.obj
AS=as CC=gcc CXX=c++ LD=ld CFLAGS=" " LDFLAGS="-Wl,--no-as-needed '-Wl,-rpath,\$ORIGIN/lib/' -Wl,-rpath,\$ORIGIN" MODEL_LDFLAGS="-L/home/rimidalv/tensorflow/bazel-bin/native_client " MODEL_LIBS="-ldeepspeech "   python ./setup.py bdist_wheel  
/home/rimidalv/anaconda3/envs/deep/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/home/rimidalv/anaconda3/envs/deep/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.5.0-alpha.5' to '0.5.0a5'
  normalized_version,
running bdist_wheel
running build
running build_ext
running build_py
file deepspeech.py (for module deepspeech) not found
copying ./__init__.py -> temp_build/deepspeech
copying ./client.py -> temp_build/deepspeech
copying ./impl.py -> temp_build/deepspeech
file deepspeech.py (for module deepspeech) not found
running egg_info
creating deepspeech.egg-info
writing deepspeech.egg-info/PKG-INFO
writing dependency_links to deepspeech.egg-info/dependency_links.txt
writing entry points to deepspeech.egg-info/entry_points.txt
writing requirements to deepspeech.egg-info/requires.txt
writing top-level names to deepspeech.egg-info/top_level.txt
writing manifest file 'deepspeech.egg-info/SOURCES.txt'
file deepspeech.py (for module deepspeech) not found
reading manifest file 'deepspeech.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'deepspeech.egg-info/SOURCES.txt'
installing to temp_build
running install
running install_lib
running install_egg_info
Copying deepspeech.egg-info to temp_build/deepspeech-0.5.0a5-py3.6.egg-info
running install_scripts
creating temp_build/deepspeech-0.5.0a5.dist-info/WHEEL
creating '/home/rimidalv/DeepSpeech/native_client/python/dist/deepspeech-0.5.0a5-cp36-cp36m-linux_x86_64.whl' and adding '.' to it
adding 'deepspeech/__init__.py'
adding 'deepspeech/_impl.cpython-36m-x86_64-linux-gnu.so'
adding 'deepspeech/client.py'
adding 'deepspeech/impl.py'
adding 'deepspeech/lib/libdeepspeech.so'
adding 'deepspeech-0.5.0a5.dist-info/entry_points.txt'
adding 'deepspeech-0.5.0a5.dist-info/top_level.txt'
adding 'deepspeech-0.5.0a5.dist-info/WHEEL'
adding 'deepspeech-0.5.0a5.dist-info/METADATA'
adding 'deepspeech-0.5.0a5.dist-info/RECORD'
removing temp_build
**(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client/python$ pip install dist/deepspeech***
Processing ./dist/deepspeech-0.5.0a5-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: numpy in /home/rimidalv/anaconda3/envs/deep/lib/python3.6/site-packages (from deepspeech==0.5.0a5) (1.15.4)
Installing collected packages: deepspeech
Successfully installed deepspeech-0.5.0a5
**(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client/python$ deepspeech -h**
deepspeech: error while loading shared libraries: libdeepspeech.so: cannot open shared object file: No such file or directory


AND

~ /tensorflow/native_client/python$ LD_DEBUG=libs deepspeech --version
     15017:	find library=libdeepspeech.so [0]; searching
     15017:	 search path=/usr/local/bin/tls/x86_64/x86_64:/usr/local/bin/tls/x86_64:/usr/local/bin/tls/x86_64:/usr/local/bin/tls:/usr/local/bin/x86_64/x86_64:/usr/local/bin/x86_64:/usr/local/bin/x86_64:/usr/local/bin		(RUNPATH from file deepspeech)
     15017:	  trying file=/usr/local/bin/tls/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/local/bin/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/local/bin/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/local/bin/tls/libdeepspeech.so
     15017:	  trying file=/usr/local/bin/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/local/bin/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/local/bin/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/local/bin/libdeepspeech.so
     15017:	 search cache=/etc/ld.so.cache
     15017:	 search path=/lib/x86_64-linux-gnu/tls/x86_64/x86_64:/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls:/lib/x86_64-linux-gnu/x86_64/x86_64:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls/x86_64/x86_64:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu/x86_64/x86_64:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu:/lib/tls/x86_64/x86_64:/lib/tls/x86_64:/lib/tls/x86_64:/lib/tls:/lib/x86_64/x86_64:/lib/x86_64:/lib/x86_64:/lib:/usr/lib/tls/x86_64/x86_64:/usr/lib/tls/x86_64:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/x86_64/x86_64:/usr/lib/x86_64:/usr/lib/x86_64:/usr/lib		(system search path)
     15017:	  trying file=/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/x86_64-linux-gnu/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/x86_64-linux-gnu/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/x86_64-linux-gnu/tls/libdeepspeech.so
     15017:	  trying file=/lib/x86_64-linux-gnu/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/x86_64-linux-gnu/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/x86_64-linux-gnu/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/x86_64-linux-gnu/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64-linux-gnu/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64-linux-gnu/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64-linux-gnu/tls/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64-linux-gnu/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64-linux-gnu/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64-linux-gnu/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64-linux-gnu/libdeepspeech.so
     15017:	  trying file=/lib/tls/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/tls/libdeepspeech.so
     15017:	  trying file=/lib/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/x86_64/libdeepspeech.so
     15017:	  trying file=/lib/libdeepspeech.so
     15017:	  trying file=/usr/lib/tls/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/tls/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/tls/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/x86_64/libdeepspeech.so
     15017:	  trying file=/usr/lib/libdeepspeech.so
     15017:	
deepspeech: error while loading shared libraries: libdeepspeech.so: cannot open shared object file: No such file or directory
(deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client/python$

**Comment by lissyx** [comment] 2019-04-15 18:52
Well I dont know what's going on but it's not searching in the appropriate places.

**Comment by lissyx** [comment] 2019-04-15 18:54
> (deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client$ PREFIX=/usr/local sudo make install

Can we please avoid doing unrelated steps ?

**Comment by lissyx** [comment] 2019-04-15 18:55
> (deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client$ TFDIR=~ /tensorflow
> (deep) rimidalv@rimidalv-desktop:~ /tensorflow/native_client$ make deepspeech

This is wrong, you don't have `TFDIR` set when running `make deepspeech`, but again, can we focus on the root issue ?

**Comment by lissyx** [comment] 2019-04-15 18:56
@rimidalv From your venv, can you:
```
$ ldd `find . -type f -name '_impl.cpython-36m-x86_64-linux-gnu.so'`
```

**Comment by rimidalv** [comment] 2019-04-15 18:59
Thank you for your time! I fixed it. I added to my PATH all paths to libs and now all work good!!! Thank you!

**Comment by lissyx** [comment] 2019-04-15 19:00
> Thank you for your time! I fixed it. I added to my PATH all paths to libs and now all work good!!! Thank you!

That feels wrong. Is it possible you have other leftovers somewhere? Could you try and find the root cause, in case someone else runs into that ?

**Comment by lissyx** [comment] 2019-04-15 19:02
> > Thank you for your time! I fixed it. I added to my PATH all paths to libs and now all work good!!! Thank you!
> 
> That feels wrong. Is it possible you have other leftovers somewhere? Could you try and find the root cause, in case someone else runs into that ?

@rimidalv There's no good reason `pip install deepspeech-gpu` would result in being unable to load `libdeepspeech.so` especially when `which deepspeech` is the expected python script installed when you install the package. We package `libdeepspeech.so` into the module and we set `RPATH` to make sure it's properly loaded when linking `_impl.cpython-36m-x86_64-linux-gnu.so`, so it should not fail like it did for you.

**Comment by rimidalv** [comment] 2019-04-15 19:03
I'll reset/clear my OS and repeat all steps to install deepspeech again. I think I did mistake from the begin.

**Comment by lissyx** [comment] 2019-04-15 19:04
> I'll reset/clear my OS and repeat all steps to install deepspeech again. I think I did mistake from the begin.

Thanks, I'll close the issue but feel free to give us feedback here or in a new issue if you spot something we need to fix!

**Closed by lissyx** 2019-04-15 19:04 UTC

**Comment by reuben** [comment] 2019-04-15 19:57
I suspect the underlying problem here was Anaconda.

**Comment by rimidalv** [comment] 2019-04-15 20:02
maybe... but Anaconda is very useful and I can't refuse it. I have one off topic more question, do you have pretrained model for 0.5 version of deepspeech? Or I need train it from the beginning?
