### ISSUE TITLE
How to implement online data-augmentation w/ the preprocessing of features?

### ISSUE THREAD

**Issue by bernardohenz** [mozilla/DeepSpeech#1815] opened 2019-01-02 17:40 UTC
Hi,

I am trying to implement audio data-augmentation (audio transformations like changes in speed/tempo/pitch, and even synthetically adding background noise), but I do not know how the best way to include this after the new preprocessing step.

Soe time ago, I implemented online augmentation right after the audio had been loaded, right before the MFCC cofs had been computed (inside ```audiofile_to_input_vector```). But now the features are extract only once per audio, unabling this online augmentation. How can I properly handle it? One option was to follow an offline dataaug strategy, generating several different versions for each audio clip; but it seems quite unefficient. Any ideas?

**Comment by reuben** [comment] 2019-01-02 17:45
Our current preprocessing pipeline is offline due to high filesystem access costs in our cluster, so for now offline augmentation is the easiest path. I want to experiment with the new tf.data APIs at some point to get a more flexible input pipeline, but I probably won't have bandwidth for it anytime soon.

**Comment by bernardohenz** [comment] 2019-01-02 18:36
@reuben 

by online I was meaning to perform data aug on-the-fly. I am already having performance issues for performing swap (when training on large training datasets that do not fit into the memory); that's why I do not like the idea of increasing even more the memory usage.

**Comment by lissyx** [comment] 2019-08-21 07:47
Looks lk ethis is a discussion, not a bug, and there's PR in flight for that. Closing.

**Closed by lissyx** 2019-08-21 07:47 UTC
